### ISSUE TITLE
Filter for File Format Version

### ISSUE THREAD

**Issue by frog23** [digital-preservation/droid#10]
This issue relates to DROID 6.01, since the Filter can not be used in DROID 6.1, see Issue #7. 
The list of identified files can be filter by each of the available columns except for the version of the File Format (and the Hash, but I can see why filtering for it doesn't make any sense). It would be useful to filter for the version as well.

**Comment by alexgreenDP** [comment]
We will review this as part of filter functionality.

**Comment by sparkhi** [comment]
I think filtering on the version number by itself is not of much use. e.g. If you filter "1.0", it would filter the "1.0" version of all formats (e.g. XML 1.0 as well as WARC 1.0) . If anything, it may be useful to have that filter as a combination with the Format name. 
As a result, I suggest this issue be closed as "won't Fix"
