### ISSUE TITLE
java.util.zip.ZipException: kml and kmz files from Govdocs Selected

### ISSUE THREAD

**Issue by ross-spencer** [digital-preservation/droid#100]
Hello Again! ^_^ 

I'm also seeing java.util.zip.ZipException errors from a small set of files in the Govdocs Selected corpus (files attached). It seems DROID is struggling to open the zip that contains the KML/KMZ content. Equivalent tools including 7-Zip don't seem to have a problem with these files (I've opened each to verify and compared against SF). 

**DROID**: 6.2.1
**Java**:

```
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) Client VM (build 25.91-b14, mixed mode, sharing)
```

**Errors**:

```
  java.util.zip.ZipException: doc.kml (C:\Working\droid-test\govdocs\govdocs_selected\govdocs_selected\KML_8\486133.kml)
  java.util.zip.ZipException: doc.kml (C:\Working\droid-test\govdocs\govdocs_selected\govdocs_selected\KMZ_2\474844.kmz)
  java.util.zip.ZipException: doc.kml (C:\Working\droid-test\govdocs\govdocs_selected\govdocs_selected\KMZ_2\502780.kmz)
  java.util.zip.ZipException: doc.kml (C:\Working\droid-test\govdocs\govdocs_selected\govdocs_selected\KMZ_2\531533.kmz)
  java.util.zip.ZipException: doc.kml (C:\Working\droid-test\govdocs\govdocs_selected\govdocs_selected\KMZ_2\543532.kmz)
  java.util.zip.ZipException: doc.kml (C:\Working\droid-test\govdocs\govdocs_selected\govdocs_selected\KMZ_2\578215.kmz)
  java.util.zip.ZipException: doc.kml (C:\Working\droid-test\govdocs\govdocs_selected\govdocs_selected\KMZ_2\683626.kmz)
  java.util.zip.ZipException: doc.kml (C:\Working\droid-test\govdocs\govdocs_selected\govdocs_selected\KMZ_2\989911.kmz)
```

[govdocs-selected-broke-kml-kmz.zip](https://github.com/digital-preservation/droid/files/375055/govdocs-selected-broke-kml-kmz.zip)

**Comment by snail1966** [comment]
[zip100.txt](https://github.com/digital-preservation/droid/files/394142/zip100.txt)
Hi Ross
That's weird - when I include the -A flag I still get the error although I do also get the detailed output as per the attached file.  This is using the command line no profile mode (exact command included in the output). Comparing a sample with 7-Zip, the output does appear to have picked up all the zipped files. 
N.B. In profile mode (assuming the "analyze ZIP etc." option is enabled), an error also occurs, albeit a different one about the DOS date "DOS date/time is earlier than 1980" in the log), and there is no output for the content files.  For historical reasons the two modes currently use different ZIP handlers - apache commons in no-profile mode and Truezip in profile mode.
We looked at various ZIP libraries in the 6.2.x release, with a view to standardising the usage, none were completely free of issues, but would like to revisit in future.
Regards, Brian

**Comment by ross-spencer** [comment]
Hi Brian, 

That is curious. 

Just to be clear for readers of this issue, but that does mean for these files, container identification isn't working. Rather than viewing them with -A for example, the files are supposed to be KML files in their own right, fmt/724, and match against the signature definition:

		<ContainerSignature Id="19070" ContainerType="ZIP">
					<Description>Keyhole Markup Language</Description>
					<Files>
						<File>
							<Path>doc.kml</Path>
							<BinarySignatures>
								<InternalSignatureCollection>
									<InternalSignature ID="19070">
										<ByteSequence Reference="BOFoffset">
											<SubSequence Position="1" SubSeqMinOffset="1" SubSeqMaxOffset="64">
								<Sequence>'kml xmlns='</Sequence>
											</SubSequence>
										</ByteSequence>
									</InternalSignature>
								</InternalSignatureCollection>
							</BinarySignatures>
						</File>
					</Files>
				</ContainerSignature>

Each of the files in that zip I sent should be impacted. 

Ross

**Comment by paulyoung84** [comment]
see also #71

**Comment by rhubner** [comment]
Not relevant anymore, We are using truezip library #144
