### ISSUE TITLE
Multiple ID values in extra columns in CSV exports

### ISSUE THREAD

**Issue by AFalut** [digital-preservation/droid#1000]
In CSV exports of DROID profiles, for cases of multiple identification, ID information (PUID, TYPE_MIME, FORMAT_NAME) beyond that of the first ID is given in extra, header-less columns on the same line. We would like instead to obtain all values for each information in the same column under the corresponding header, the way they are displayed in the DROID GUI.

Example of actual output: "fmt/1827" in the PUID column, "application/vnd.openxmlformats-officedocument.wordprocessingml.document" in the MIME_TYPE column, "DOCX Strict OOXML Document" in the FORMAT_NAME column, "2007 onwards" in the FORMAT_VERSION column, then "fmt/412", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "Microsoft Word for Windows" and "2007 onwards" in unnamed columns.

Example of requested output: "fmt/1827 | fmt/412" in the PUID column, "application/vnd.openxmlformats-officedocument.wordprocessingml.document | application/vnd.openxmlformats-officedocument.wordprocessingml.document" in the MIME_TYPE column, etc.

**Comment by sparkhi** [comment]
Hi @AFalut 
I think the case you mention is same as described in https://github.com/digital-preservation/droid/issues/861

If so, we have actually made a change which will go into 6.7.0 (it is currently available in the release candidate if you wish to try out) which adds headers to those columns with a running suffix (e.g. PUID1, MIME_TYPE1 etc.) 

Let us know your feedback if you try it out. 

Many thanks,

**Comment by AFalut** [comment]
Hi @sparkhi 
Thank you for the answer, it is indeed the same case.
As we use the CSV exports to import metadata to our SIP preparation tool, having the option to gather all values for each information in a single column would be ideal; is there a chance this could be considered for a future release?
In any case, we gave the release candidate a first try and will perform further tests on this feature.

**Comment by sparkhi** [comment]
Hi @AFalut 
That is interesting to know. When implementing we felt it was necessary to keep the fields atomic to avoid additional parsing need as well as the logic about correspondence between multiple PUIDs. Hence we decided that it would be best to have the correct headers, thus also making it a correct CSV which can be opened in other tools like MS-Excel 

I'll keep in mind the suggestion about merging the multiple identifications into the same column, however we do not intend to change it at this point. Hope that's not too much of an inconvenience.

Many thanks,

**Comment by AFalut** [comment]
Hi @sparkhi 
Thank you for the information; we'll let you know if we have anything else to report about the RC.
