### ISSUE TITLE
Are we changing from Java 11 to a newer version?

### ISSUE THREAD

**Issue by kathaurielle** [digital-preservation/droid#1003]
Hello, I've had this email, please can you let me know what to advise him? Thanks v much!:

I have been trying to get Droid installed at Essex Record Office for what seems like an eternity. The latest attempt has stalled because our I.T
. department are not happy about having OpenJDK v11.0.18 installed. Their reasoning is that this goes unsupported this month, which I can understand.
 
Is there any plan to use a newer version of OpenJDK in any future releases? I can see from your pages that the most recent version of Droid is 6.7, but everything I can see still points to the requirements of having Java or JDK 8 – 11 installed.

**Comment by steve-daly** [comment]
Yes, DROID works with Java 8 to Java 11.  I believe that Oracle's paid support for Java 11 goes out of mainstream support and into extended support at the end of this month, but I don't think there's an end-of-support date imminent for OpenJDK or the Adoptium release that's bundled with DROID.  For example, OpenJDK 8 is still supported until Nov 2026 https://access.redhat.com/articles/1299013

**Comment by kathaurielle** [comment]
Thanks... our website infers that it's Java 11 we're running, is it misleading https://www.nationalarchives.gov.uk/information-management/manage-information/preserving-digital-records/droid/ , is it not 11?

**Comment by kathaurielle** [comment]
Oh, so Java 11 is going out of support, but  Java OpenJDK 11 is not? (sorry).

**Comment by steve-daly** [comment]
It's still all Java (and all Java 11) but there are different distributions with different support offerings.

**Comment by kathaurielle** [comment]
ok, will invite them to chat to you here.

**Comment by mpbraendle** [comment]
RHEL 8 Support for OpenJDK 11 ends October 2024 ...
I think it is urgent that Droid supports higher OpenJDK versions.

**Comment by steve-daly** [comment]
Thanks for the prompt. We'll try to move to OpenJDK 17 in the next release.  Many people, especially those on Linux, do run on a modern Java anyway (if that's what's installed on a machine) but we hadn't formally qualified anything later than 11.  We've been running our build and unit tests on JDK 17 (as well as 8 and 11) for quite some time anyway, but we'll see if we can complete our full testing on JDK 17, and bundle an OpenJDK 17 JRE with the Windows version.
