### ISSUE TITLE
Does Droid support file renaming to correct filetype?

### ISSUE THREAD

**Issue by Alister-Zeus** [digital-preservation/droid#1005]
Whilst I can scan a large folder of mis-extensioned  files (all files were downloaded as .html rather than .zip/.rar/jpg/gif etc) I can't see a way to correct this except to export a filtered by mismatch csv and manual covert that to a batch file and then run that

**Comment by steve-daly** [comment]
Many formats have a range of possible extensions too, so there's often not a 'correct' extension to be applying. Processing this in a batch outside of DROID would definitely be the best option.   As @sparkhi says, there's a principle in DROID that it can do no harm to the files it's characterising (which reassures organisations installing it) so we expect to continue with that approach.

**Comment by ross-spencer** [comment]
@Alister-Zeus I discovered this code from @tw4l the other day and it may fulfill this need for you? https://github.com/tw4l/addext -- certainly worth a look.

**Comment by sparkhi** [comment]
Hi @Alister-Zeus Can we close this issue?

**Comment by Alister-Zeus** [comment]
yes
