### ISSUE TITLE
fmt/40 file reports different format name in GUI and API

### ISSUE THREAD

**Issue by sparkhi** [digital-preservation/droid#1011]
One of the Microsoft word document reports different format names in GUI and API. 

In API, it is 
```
Format Name: Microsoft Word 97 OLE2
Puid: fmt/40
Identification Method: Container
Extension: 
Extension Mismatch: true
```
whereas in GUI, it is 

![image](https://github.com/digital-preservation/droid/assets/4743002/bdc67b31-7287-4526-b88c-639db9c3c98e)

**Comment by pwinckles** [comment]
This is true for all container formats. Only SubmissionGateway handles them correctly, which is a huge hassle to setup. See the implementation in FITS: https://github.com/harvard-lts/fits/pull/388/files#diff-13712da0407562c3b98920904b87e1de45ca9265edb511c0852d8a078da474c4
