### ISSUE TITLE
Generating hash value for files in command line using Droid

### ISSUE THREAD

**Issue by kathaurielle** [digital-preservation/droid#1016]
hello, can anyone advise re this user query please?:

I would like to generate the sha1 hash for files when running the Droid in command line. I put the profile option “-Pr 'hashAlgorithm=sha1'” in command line as below, however the hash column in CSV output doesn’t have any hash values. Is there anything I did wrong?

java –DdroidTempDir=”/srv/droid/tmp” -DdroidUserDir=”/srv/droid/udir” –DdroidLogDir=”/srv/droid/logDir” -jar “/srv/droid/tool/droid-command-line-6.7.0.jar”  -a “/srv/data/xyz.zip” -R -p “/srv/profile/resut.droid -Pr “hashAlgorithm=sha1”

Thank you,

**Comment by sparkhi** [comment]
The command line is correct. There is an additional default property about generating hash which is `False` by default, making it true should give you desired result. 

i.e. the following command should work 
`java –DdroidTempDir=”/srv/droid/tmp” -DdroidUserDir=”/srv/droid/udir” –DdroidLogDir=”/srv/droid/logDir” -jar “/srv/droid/tool/droid-command-line-6.7.0.jar” -a “/srv/data/xyz.zip” -R -p “/srv/profile/resut.droid -Pr "generateHash=true" “hashAlgorithm=sha1”`
