### ISSUE TITLE
Appending the file identification result to output file

### ISSUE THREAD

**Issue by kathaurielle** [digital-preservation/droid#1017]
...and this one please?

I want to save the result of Droid file identification to files in different directory in the same CSV output file, such as 
1.	I have files locate in different directories C:/files/1 and C:/files/2
2.	I run the DROID on files in directory “C:/files/1” first and save the output to C:/output/result.csv.
3.	Then I run the DROID on files in directory “C:/files/2” and save the output to C:/output/result.csv.
When looking at the content in result.csv file, it includes only the file identification result for files in directory “C:/files/2”. I think the output in step 3 overwrites the output in step 2 in result.csv. I wonder is there any way to append the output in step 3 to the result.csv which already has the output from step 2?

**Comment by sparkhi** [comment]
Exporting the profiles one after other will surely overwrite the file. There is no functionality in DROID to append to existing files. This would also be problematic as we do not know whether the previous export had exactly same columns and similar structured data.
However,
If you have both profiles open in Droid, and you click export, the export dialog shows up with a checkbox to choose either one or both of the profiles. If you choose both profiles, the export file will include results from both profiles.

Hope this helps,

**Comment by sparkhi** [comment]
Can this issue be closed?
