### ISSUE TITLE
NoProfileMode: Not giving up file handles because of this code?

### ISSUE THREAD

**Issue by ross-spencer** [digital-preservation/droid#102]
From line 183 onwards https://github.com/digital-preservation/droid/blob/66ca5162bcd09c39dce12379d7c49aea835e960c/droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/NoProfileRunCommand.java#L183: 

```
          String fileName = null;
          for (File file : matchedFiles) {
              try {
                  fileName = file.getCanonicalPath();
              } catch (IOException e) {
                  throw new CommandExecutionException(e);
              }
              URI uri = file.toURI();
              RequestMetaData metaData =
                  new RequestMetaData(file.length(), file.lastModified(), fileName);
              RequestIdentifier identifier = new RequestIdentifier(uri);
              identifier.setParentId(1L);

              InputStream in = null;
              IdentificationRequest<File> request = new FileSystemIdentificationRequest(metaData, identifier);
              try {
                  request.open(file);
                  IdentificationResultCollection results =
                      binarySignatureIdentifier.matchBinarySignatures(request);

                  resultPrinter.print(results, request);
              } catch (FileNotFoundException fnfe) {
                 log.error("error processing files", fnfe);
                 throw new CommandExecutionException(fnfe);
              } catch (IOException e) {
                  throw new CommandExecutionException(e);
              } finally {
                  if (in != null) {
                      try {
                       request.close();
                       file=null;
                       in.close();

                      } catch (IOException e) {
                          throw new CommandExecutionException(e);
                      }
                  }
              }
          }
```

We set:

```
InputStream in = null;
```

But we never use it again - we check to see if it's !null in the finally block, but it shouldn't enter here because it's never set to anything else. 

```
if (in != null) {
```

The finally block looks to be there to give up the file handles we have open but it of course never enters, and if it would, we only ask for the pointer to the file to be set to null, we never fully release it with an f.close() like function. 

I'm seeing in NoProfileMode that file handles aren't being released which is causing them to just keep creeping up, eating up memory: https://twitter.com/beet_keeper/status/756271673347678208 unfortunately I can't test this right now as I haven't a Java development environment readily available.

**Comment by snail1966** [comment]
Thanks for pointing this out Ross, this was a leftover from the refactoring to integrate Byteseek 2 - will be removed in next release.  The  FileSystemIdentificationRequest now obtains a Byteseek FileReader when the open() method is called and releases it on close (reader request.close() in the finally block).
Regards, Brian

**Comment by snail1966** [comment]
Have bundled this with the fix for issue 97 - this has now been pushed to the master branch for inclusion in the next release.
