### ISSUE TITLE
819913.eps file in govdocs corpus - correctly matched, but on an incorrect basis?

### ISSUE THREAD

**Issue by richardlehane** [digital-preservation/droid#104]
In the govdocs corpus, DROID gives a x-fmt/91 match for the file govdocs_selected\EPS_9\819913.eps (file attached, but renamed with a .pdf extension so github would accept it - [819913.eps.pdf](https://github.com/digital-preservation/droid/files/410457/819913.eps.pdf)).

The match is right but could be construed as technically incorrect as the last bytes of the file don't precisely match the PRONOM signature. The last bytes of the file are: 25 45 4F 46 0A 0A . The EOF signature in PRONOM is 2525454F46(0D|0A|0D0A) at zero offset. 

Suggest amending the PRONOM signature so that the last choice is (0D|0A|0D0A|0A0A) and also checking the DROID algo for these cases.

p.s. this comes out of @ross-spencer 's  DROID/sf govdocs testing

**Comment by Dclipsham** [comment]
Can confirm. Have run through some signature scenarios with following outcomes:
EOF: 2525454F46(0D|0A|0D0A) = ID # as it is now
EOF: 2525454F46(0D|0D0A) = **no ID** # no sole 0A in either/or block
EOF: 2525454F46(0D|0A) = **no ID** # all fragment in either/or block same length
EOF: 2525454F46(0D|0A|FFFF) = ID # arbitrary 2 byte fragment in either/or block

So for me it looks like the length of the longest fragment in the either/or block is affecting how the other potential fragments in the block are processed.

**Comment by Dclipsham** [comment]
As an aside, I agree that we should add 0A0A as a further option, but also keen to get the DROID behaviour fixed

**Comment by snail1966** [comment]
This is fixed in the code base at https://github.com/snail1966/droid/tree/multiFragmentInstances - which also addresses issue #82.  This is due to be incorporating into the next release, subject to further testing.
