### ISSUE TITLE
Create a priority order for PDF over TTF (x-fmt/453)

### ISSUE THREAD

**Issue by ross-spencer** [digital-preservation/droid#106]
The attached file comes from Govdocs Select and returns a multiple identification:

![image](https://cloud.githubusercontent.com/assets/1880412/17686643/71a59914-63c2-11e6-97a7-689ee9b4c29d.png)

Looking via Adobe Acrobat for the existence of embedded fonts it seems there are some, and they might be causing the confusion (the font stream appears right at the beginning of the file) and does match x-fmt/453. 

Suggest creating a priority relationship between PDF and TTF to avoid similar outcomes. 

[224727.pdf](https://github.com/digital-preservation/droid/files/419390/224727.pdf)

**Comment by paulyoung84** [comment]
Hi Ross, thanks for spotting this and letting us know about it. We will add this to the next release.

**Comment by Dclipsham** [comment]
TTF now has lower priority than all PDF entries as of v88
