### ISSUE TITLE
Is this a normal speed...? 

### ISSUE THREAD

**Issue by kathaurielle** [digital-preservation/droid#1078]
The user says:

'it’s taken 3 hours for 1.74GB data.w managed to get a CD to have a DROID profile run directly from it but it’s taken 3 hours for 1.74GB data. Is this a normal amount of time?'

I think it is OK, any thoughts?

(Posting for the user as hopefully this is a yes/no answer).

**Comment by DavidUnderdown** [comment]
Well if it's got that much data on it must be a DVD not a CD, or there's a zip involved. Speed would be determined by the optical drive's data rate which will be slower than a hard drive usually. If it would take a similar time to copy the data to hard drive first then that's the limiting factor.

**Comment by steve-daly** [comment]
DROID normally manages to process the files as fast as the network/drive speed will allow (e.g. it can run at almost wire speed when processing over a Gigabit network.  A test would be to try to copy the files instead to see if the speed is similar or worse.  It will be affected by whether checksum/hash generation is enabled as that would guarantee that every byte needed to be read.

**Comment by steve-daly** [comment]
@kathaurielle We can talk some more with the reporter if you'd like (or if they want to comment on here).  You can't get 1.74GB of data on a CD so something isn't right.
