### ISSUE TITLE
DROID 6.6.1 not providing hashes. 

### ISSUE THREAD

**Issue by kathaurielle** [digital-preservation/droid#1079]
Hello, a DROID user has asked me to post for them... I suggested some basic checks which didn't work. this is where we are:

Enquirer:
I am running Droid v.6.6.1 and am having a bit of trouble with generating hash checks. I have it selected in preferences to generate md5 hashes. 

Me:
I’m sorry to hear you’re having these problems. There have been a couple of enquiries regarding this problem but never confirmation if the advice given has solved the problem. So far an idea is that DROID could be installed on a connecting server and not on your main computer. Have you recently reinstalled DROID and is it installed on the computer itself instead of loading from another server? Could you generally tell us a bit more about the setup of your DROID and if it has generated hashes before since this specific installation? 
 
Another thing to make sure is after selecting the box “Generate hash for each file using” and pressing “OK”, a new profile must be created before scanning your files to work with the updated preferences- but I suspect this isn’t the case with you? 

Enquirer:
I can confirm Droid is running from my local computer – in fact due to the cyber attack last year my work computer isn’t connected to any wider servers so I am very confident about that! I have an old creaky mac at home and I downloaded v.6.7.0 which produced md5 hashes. Do you know if this was something that was changed between v.6.6.1 and v.6.7.0? Unfortunately due to the cyber attack I also can’t re-download Droid at the moment on this computer.

I will send the link to the enquirer, so that they can keep an eye out for a reply, as I'm off tomorrow. Thank you, KP.

**Comment by steve-daly** [comment]
What behaviour do you get currently?  You have "generate hash" and "MD5" set in the preferences (and have made a new profile)? But what happens in practice?  Do you just not get anything in the HASH column?

**Comment by charlie-morgan** [comment]
Well as is always the case it seems to be working fine, even though I don't think I am doing anything different! I was previously setting the preferences for md5 and then starting a new profile but it now seems to be working fine. Very confusing, but thank you for your help! Charlie
