### ISSUE TITLE
Request for UTF-8 BOM export to csv

### ISSUE THREAD

**Issue by paulyoung84** [digital-preservation/droid#108]
Request by Ross Spencer, https://groups.google.com/forum/#!topic/droid-list/897MdRo06uI,

**Comment by rhubner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#108 Request for UTF-8 BOM export to csv](https://trello.com/c/9KEhZGhi/30-108-request-for-utf-8-bom-export-to-csv)

**Comment by DavidUnderdown** [comment]
In test

**Comment by alexgreenDP** [comment]
Closed in 6.4.
