### ISSUE TITLE
DROID 6.7 not installing on Windows 11. 

### ISSUE THREAD

**Issue by kathaurielle** [digital-preservation/droid#1085]
Hello, I've been assisting a user who's having problems installing DROID. I've not sorted it, so posting our exchange here....It's as if it can't find a java file, but I've checked it's the java embedded version. The enquirer might join in here. Please could you advise?

**- Enquirer:**  Hello, I have been using DROID frequently for 2 years.
Now, with the change of computer, I am trying to install DROID again, but it is not possible, since after extracting the files, I do not have access to any file to run the program: If there is any information you can provide me, I would greatly appreciate it.

![image](https://github.com/digital-preservation/droid/assets/46964067/e0ca9a6a-e9e6-4609-af42-c83c5f29c040)

**- Me:**  asking if the yare using a Mac etc- they aren't. 

**- Enquirer:**  Thank you for your message. I'm not using a MAC. I use Windows 11. I will try to explain what happens when I double click on the files referred to in the "Running DROID.txt" file. When I double click on the DROID.sh file, a message appears telling me to select an application to open this "sh" file:

![image](https://github.com/digital-preservation/droid/assets/46964067/b9d637fb-53e2-4d73-be31-6f56f923a090)

When I double click on the DROID (batch file), it appears a message saying that Windows cannot find "javaw" and to make sure that the name is correctly written. 

![image](https://github.com/digital-preservation/droid/assets/46964067/865cbb7c-ade0-4e8f-883c-3897029c7709)

![image](https://github.com/digital-preservation/droid/assets/46964067/84df698c-c854-4c7f-8844-74aa20ac87fa)

**- Me:** I see, thanks for such a comprehensive response. We should check if you’ve downloaded the correct version of DROID; DROID 6.5 onwards provides two download options for users. The first is embedded with Java OpenJDK 11 for Windows users and does not require Java to be installed to run. The second can be run on any system with Java 8 to 11 installed. Please can you confirm you’ve downloaded the version with java embedded? It can be downloaded via this page:  ...

**-Enquirer:** Thank you, once again. Even with the version with JAVA embedded, I can't install the DROID. When I compare the files, in the uncompressed folder, that appeared in the video that introduced me to DROID, two years ago (at the time without any installation problems):
![image](https://github.com/digital-preservation/droid/assets/46964067/f1e9316a-035e-4385-b008-f7bcfc1c4933)

printscreen from vídeo that shows how to install DROID

and the files that are in the current uncompressed folder, what I see is that now I still have a compressed file, whereas before it was a file that allowed me to open the program.
![image](https://github.com/digital-preservation/droid/assets/46964067/be21a1b5-506c-4ebe-8f24-6f9e56fe9b01)

printscreen from the actual uncompressed folder. But I won't keep bothering you. Maybe it's something else that I'm not doing well.

**Comment by sparkhi** [comment]
Droid comes with 2 distributables, they are also available from this page : https://github.com/digital-preservation/droid/releases/tag/droid-6.7.0

- **droid-binary-6.7.0-bin-win32-with-jre.zip**
    This zip contains the Java runtime for Windows. The droid.bat script from this distribution refers to the java version within the distributable. If you use this distributable, you will not have the droid.sh file and you will also have a folder called jre which contains the Java runtime. 
    
- **droid-binary-6.7.0-bin.zip**    
    This zip is a generic zip which can be used on any of the supported OSs, however it relies on Java being already installed on the machine where Droid is running.  
    
The screenshots posted makes me think that you have used the second zip. This relies on Java being already installed on the machine. You could try opening a "command prompt"  and execute "java -version" to see if Java is already installed on your machine. 

About the files still appearing to be compressed. (droid-command-line-6.7.0, droid-tools-6.7.0  and droid-ui-6.7.0) they are the JAR file which Windows is showing with an "archive" icon, I can assure you that they are correct files.

I think the best option would be to get the version with embedded java and unzip it to another folder. Once you are happy that it works, you can delete the folder where it is not working .

**Comment by kathaurielle** [comment]
Thank you sparkki, all sorted now, I think it was the version!

**Comment by kathaurielle** [comment]
.
