### ISSUE TITLE
File size Limit?

### ISSUE THREAD

**Issue by luvnrocs** [digital-preservation/droid#109]
There seems to be a file size limit in what DROID can identify. I ran some 3 gb wav files through with no problem, but 6 gb wav files don't seem to verify.
![test](https://cloud.githubusercontent.com/assets/21184989/17875511/b624b150-68a0-11e6-904d-3af889fcbe3e.png)

**Comment by Dclipsham** [comment]
Thanks for the report. Are you able to provide a screen grab from a hex editor of the header for one of the files (i can provide detailed instructions if wanted). 

I was under the impression that plain WAV couldn't be bigger than ~4GB so am curious to see if they have any special structure or RIFF extension - perhaps an RF64 variant we need to add....

David

**Comment by luvnrocs** [comment]
Can you provide those instructions?

I tired to open the file in Text Wrangler but it errors because the file is too big.

Thanks,

Jenn Morris
Digital Imaging Manager
MIT Libraries
617.253.7286
j_morris@mit.edu<mailto:j_morris@mit.edu>

Keep up to date on the MIT Libraries<http://libraries.mit.edu/news/subscribe/>!

On Aug 23, 2016, at 4:26 AM, David Clipsham <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the report. Are you able to provide a screen grab from a hex editor of the header for one of the files (i can provide detailed instructions if wanted).

I was under the impression that plain WAV couldn't be bigger than ~4GB so am curious to see if they have any special structure or RIFF extension - perhaps an RF64 variant we need to add....

David

**Comment by Dclipsham** [comment]
No problem, thanks Jenn.
1. Download HxD - it's just my preferred hex editor as its simple and lightweight -there's a portable and an installable version here:
https://mh-nexus.de/en/downloads.php

2. Open it up and drag one of the files into the window (or File > Open > Browse to and select your file)

3. Next, use your keyboard's Print Screen button to capture an image of the screen, open MS Paint or similar graphic application, paste in the captured image, save it and either post it here or email to pronom@nationalarchives.gsi.gov.uk

I hope this helps. Let me know if anything is unclear.

David

**Comment by Dclipsham** [comment]
![rf64](https://cloud.githubusercontent.com/assets/2189778/17976376/1429e1bc-6ae5-11e6-95ba-3f223fab0072.png)

Thanks Jenn, your image is posted above. 
Your file is an RF64 file rather than a WAV. As mentioned in my initial response, plain WAV is a 32 bit format and its file size cannot exceed 4GB, so it looks like your audio tool has automatically created an RF64 instead. RF64 is effectively a WAV, but extended to allow 64 bit addressing, meaning a theoretical file size limit of around 16 Exabyte.

So theoretically your file should identify as fmt/712 - https://www.nationalarchives.gov.uk/PRONOM/fmt/712

However, I can see that the 5th-8th bytes are different from that which I've specified in the PRONOM entry, which means I'll need to update PRONOM to ensure your files identify. I'm planning a release in mid-late September and I'll include the adjustment there.

Can you tell me what audio application/utility was used to create these files?

**Comment by luvnrocs** [comment]
I just emailed the vendor who performed the work and will get back to you as soon as I hear from him.

Jenn Morris
Digital Imaging Manager
MIT Libraries
617.253.7286
j_morris@mit.edu<mailto:j_morris@mit.edu>

Keep up to date on the MIT Libraries<http://libraries.mit.edu/news/subscribe/>!

On Aug 25, 2016, at 12:04 PM, David Clipsham <notifications@github.com<mailto:notifications@github.com>> wrote:


[rf64]<https://cloud.githubusercontent.com/assets/2189778/17976376/1429e1bc-6ae5-11e6-95ba-3f223fab0072.png>

Thanks Jenn, your image is posted above.
Your file is an RF64 file rather than a WAV. As mentioned in my initial response, plain WAV is a 32 bit format and its file size cannot exceed 4GB, so it looks like your audio tool has automatically created an RF64 instead. RF64 is effectively a WAV, but extended to allow 64 bit addressing, meaning a theoretical file size limit of around 16 Exabyte.

So theoretically your file should identify as fmt/712 - https://www.nationalarchives.gov.uk/PRONOM/fmt/712

However, I can see that the 5th-8th bytes are different from that which I've specified in the PRONOM entry, which means I'll need to update PRONOM to ensure your files identify. I'm planning a release in mid-late September and I'll include the adjustment there.

Can you tell me what audio application/utility was used to create these files?

**Comment by luvnrocs** [comment]
Hi David -

He used Adobe Audition 6 on the Mac platform at 96Khz, 24 bit.

Jenn Morris
Digital Imaging Manager
MIT Libraries
617.253.7286
j_morris@mit.edu<mailto:j_morris@mit.edu>

Keep up to date on the MIT Libraries<http://libraries.mit.edu/news/subscribe/>!

On Aug 25, 2016, at 12:10 PM, Jenn Morris <j_morris@mit.edu<mailto:j_morris@mit.edu>> wrote:

I just emailed the vendor who performed the work and will get back to you as soon as I hear from him.

Jenn Morris
Digital Imaging Manager
MIT Libraries
617.253.7286
j_morris@mit.edu<mailto:j_morris@mit.edu>

Keep up to date on the MIT Libraries<http://libraries.mit.edu/news/subscribe/>!

On Aug 25, 2016, at 12:04 PM, David Clipsham <notifications@github.com<mailto:notifications@github.com>> wrote:


[rf64]<https://cloud.githubusercontent.com/assets/2189778/17976376/1429e1bc-6ae5-11e6-95ba-3f223fab0072.png>

Thanks Jenn, your image is posted above.
Your file is an RF64 file rather than a WAV. As mentioned in my initial response, plain WAV is a 32 bit format and its file size cannot exceed 4GB, so it looks like your audio tool has automatically created an RF64 instead. RF64 is effectively a WAV, but extended to allow 64 bit addressing, meaning a theoretical file size limit of around 16 Exabyte.

So theoretically your file should identify as fmt/712 - https://www.nationalarchives.gov.uk/PRONOM/fmt/712

However, I can see that the 5th-8th bytes are different from that which I've specified in the PRONOM entry, which means I'll need to update PRONOM to ensure your files identify. I'm planning a release in mid-late September and I'll include the adjustment there.

Can you tell me what audio application/utility was used to create these files?

**Comment by Dclipsham** [comment]
Thanks again Jenn, that will help me to reproduce. I'll soon provide a test signature so you can confirm the fix works for you.

David

**Comment by luvnrocs** [comment]
Great. Thanks for your help.

Jenn Morris
Digital Imaging Manager
MIT Libraries
617.253.7286
j_morris@mit.edu<mailto:j_morris@mit.edu>

Keep up to date on the MIT Libraries<http://libraries.mit.edu/news/subscribe/>!

On Aug 25, 2016, at 2:44 PM, David Clipsham <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks again Jenn, that will help me to reproduce. I'll soon provide a test signature so you can confirm the fix works for you.

David

**Comment by Dclipsham** [comment]
No problem, can I credit MIT Libraries with the contribution in our release notes? https://www.nationalarchives.gov.uk/aboutapps/pronom/release-notes.xml

**Comment by luvnrocs** [comment]
Sure.

Jenn Morris
Digital Imaging Manager
MIT Libraries
617.253.7286
j_morris@mit.edu<mailto:j_morris@mit.edu>

Keep up to date on the MIT Libraries<http://libraries.mit.edu/news/subscribe/>!

On Aug 25, 2016, at 2:51 PM, David Clipsham <notifications@github.com<mailto:notifications@github.com>> wrote:


No problem, can I credit MIT Libraries with the contribution in our release notes? https://www.nationalarchives.gov.uk/aboutapps/pronom/release-notes.xml

**Comment by Dclipsham** [comment]
RF64 signatures adjusted in release v88 so your files should now ID, but do let me know if not. I'll keep this ticket open for a few days.
