### ISSUE TITLE
DROID 6.7 stuck in initialising profile on a MAC

### ISSUE THREAD

**Issue by kathaurielle** [digital-preservation/droid#1098]
Hello, I have a user with the above problem. He has it scanning both files of a Hard Drive and desktop.- he clicks start and nothing happens.  They say they have Java. Pics are attached. Any advice, please?

<img width="677" alt="kp1" src="https://github.com/digital-preservation/droid/assets/46964067/b0e19238-4bca-4529-af14-d43e13f7cd41">
![kp)](https://github.com/digital-preservation/droid/assets/46964067/08628358-f04f-40dd-8238-df6392923eaa)

**Comment by kathaurielle** [comment]
<img width="677" alt="kp1" src="https://github.com/digital-preservation/droid/assets/46964067/fd8a2ba7-59f0-4e5a-8a5b-c12904ba7a6e">

**Comment by kathaurielle** [comment]
![kp)](https://github.com/digital-preservation/droid/assets/46964067/592644ee-b5ee-440a-b475-d95a8cdfad3f)

**Comment by steve-daly** [comment]
Can the user press the "Open" button to the right of the "Log Location" field in the first screenshot, and see what the end of the log file looks like.

**Comment by kathaurielle** [comment]
Thanks have asked, and suggested they join in here.

**Comment by gibco** [comment]
Look, I need to examine this file but when I select it and click start, the system does not process the analysis and does not generate the report.

<img width="916" alt="Capture de Pantalla 2024-04-23 a la(s) 10 33 55 a m" src="https://github.com/digital-preservation/droid/assets/65411430/389d618e-133a-4849-a5ef-827f26f867b4">


<img width="890" alt="Capture de Pantalla 2024-04-23 a la(s) 10 34 18 a m" src="https://github.com/digital-preservation/droid/assets/65411430/3d2e5e0d-92ae-4c90-a0e7-4597b1c8da05">

**Comment by sparkhi** [comment]
Hi @gibco 

We believe the log file will have more details about the errors if there are any. 
If you go to the "About Droid" dialog, open the log location and send the log file to us, we can take a look. 

Many thanks,

**Comment by gibco** [comment]
Hello I share the files


Thanks a lot for your help


<img width="658" alt="Captura de Pantalla 2024-04-23 a la(s) 9 11 52 p m" src="https://github.com/digital-preservation/droid/assets/65411430/5b6b2db0-9bf0-4c6c-bc93-3086175f69fa">


[logs_droid.zip](https://github.com/digital-preservation/droid/files/15085303/logs_droid.zip)

**Comment by steve-daly** [comment]
Thanks. This looks to be an issue with the underlying database when working with the "Latin American Spanish" localisation setting on your machine.   DROID should work with different languages but it looks as if there's a known issue with the underlying database when working with this particularly country setting, as it uses an unusual country code ("419") rather than the normal two letter county code (e.g. GB or ES).   Do you have the option for setting the region of your machine more specifically to a defined country.

**Comment by sparkhi** [comment]
As a workaround, you could set the language and country as a parameter on JVM that is running Droid. This will get you past the hurdle but it would result in situations for which we have not tested 100% 

If you want to try, you can change line number 151 in the file droid.sh to be as given below (including country as Colombia and language as spanish) : 
`java $OPTIONS -Duser.country=CO -Duser.language=es -jar "$DROID_HOME/droid-ui-6.7.0.jar"`

and Droid should launch the UI as normal. 

**Please Note**: This would be very specific to your case, whenever we release a new version, we always default to picking language and country code from the underlying operating system, If you can set these on your OS, that would be better than modifying 'droid.sh' file

**Comment by gibco** [comment]
List I have made the line change
<img width="1304" alt="cambio de linea" src="https://github.com/digital-preservation/droid/assets/65411430/54c1e82a-2697-4c04-ac76-6c1a63d3ea36">
So..

1. I open droid
2. create profile
3. I search for files
4. I click start
5. does not process
Note:

![Screen Shot 2024-04-24 at 2 07 08 PM](https://github.com/digital-preservation/droid/assets/65411430/0692c3bf-7643-478f-ab2c-52b9ce73672a)


note: reviewed
and changed the locale. I'm going to restart the machine and tell you

**Comment by gibco** [comment]
Hello, I already modified it and it worked perfectly. Thank you for your cooperation

![Screen Shot 2024-04-24 at 2 18 12 PM](https://github.com/digital-preservation/droid/assets/65411430/249742cf-f744-489d-9c72-8280aefc597b)


Note: I left the file modified on line 151, and it worked the same... but I will leave it as it was originally...

**Comment by kathaurielle** [comment]
Great news Jhon, thanks for letting us know.
