### ISSUE TITLE
Creating priority for pdf/x over pdf

### ISSUE THREAD

**Issue by andreakb** [digital-preservation/droid#110]
Hello,
I am looking at the attached file from the govdocs corpus.

[272791.pdf](https://github.com/digital-preservation/droid/files/438192/272791.pdf)

It  multi-identifies as fmt/144 (Acrobat PDF/X - Portable Document Format - Exchange 1:1999) and fmt/16 ( Acrobat PDF 1.2 - Portable Document Format), which, looking around, make sense because PDF/X is based on PDF 1.2, and looking at the [documentation](http://www.npes.org/Portals/0/standards/pdf/PDF-X-Application-Notes_V4-Sep06.pdf) I could find about later versions of pdf/x 

**2.3 Identification and conformance**
A PDF file is identified by a header, the first line of which is a PDF comment that begins with “%PDF-” and is followed by a version number. While each conformance level requires that files conform to a specific version of PDF, they also state that the version number in the first line of the header is not relevant for determining PDF/X
compliance. 

A conforming PDF/X-1a:2003 file is identified by:
a) being a PDF file; and
b) having the GTS_PDFXVersion key in the Info dictionary with a value of (PDF/X-1a:2003)

A conforming PDF/X-2:2003 file is identified by:
a) being a PDF file;
b) having the GTS_PDFXVersion key in the Info dictionary with a value of (PDF/X-2:2003)

A conforming PDF/X-3:2003 file is identified by:
a) being a PDF file;
b) having the GTS_PDFXVersion key in the Info dictionary with a value of (PDF/X-3:2003)

In pronom, fmt/144 is listed as being a subtype as fmt/16, and it looks like the subtype specification is the case for other versions of pdf/x as well. I am wondering if the "is the subtype of" is related to priority at all? Because it seems like (at least in this case), without priority logic in place, a pdf/x will identify as both the pdf version in the header and the pdf/x version specified in the info dictionary . 

Thank you!

**Comment by Dclipsham** [comment]
Hi Andrea,
Yes, this looks like an oversight on our part. If you look at, for example, PDF/X-1a:2001 - http://www.nationalarchives.gov.uk/PRONOM/fmt/157 we have set the priority over PDF 1.3, and all of these PDF subtypes should have priority over their respective supertypes. I'll correct each of them in the September release.
Subtype doesn't do anything from an ID point of view, it's just a way of representing relationships between formats. We do need the 'has priority over' too

You're ANZ aren't you?

David

**Comment by andreakb** [comment]
Thanks for that, David! The subtype explanation helps me, too.  I am at ANZ.

**Comment by Dclipsham** [comment]
This didn't make September release as I ran out of time to get it through our back end systems, but I'll either do a micro-release in October or roll it in with the larger scheduled November release. Apologies!

**Comment by Dclipsham** [comment]
fixed in march release. sorry for the delay
