### ISSUE TITLE
Cancelling the preferences dialog still makes changes to the preferences

### ISSUE THREAD

**Issue by sparkhi** [digital-preservation/droid#1100]
**Steps to reproduce**:

1. Launch preferences
2. Uncheck one of the zip processing
3. Click "Cancel"
4. Open preferences again, the checkbox from step 2 remains unchecked (i.e. unknowingly some setting has changed - BUG) 

Seen as far back as v6.5.2

**Comment by steve-daly** [comment]
Thanks.  This is interesting.  It looks like the subtle difference between the Cancel and OK buttons is that if you press OK the settings survive a restart of the application, whereas if you press Cancel they apply during the session but don't survive a restart.  Not as intended though, as you say.

**Comment by sparkhi** [comment]
It looks like the setting change does not take effect, but it is misleading to the user.
