### ISSUE TITLE
Integrate skeleton suite into unit tests

### ISSUE THREAD

**Issue by alexgreenDP** [digital-preservation/droid#111]
Ross wrote:

I'd create a new suite for your own testing purposes. This is now here: https://github.com/exponential-decay/skeleton-test-suite/releases/tag/skeleton-test-suite-2016-01-21-sig-file-v84 

For a set of container skeletons you will need release v82 as I haven't written a handler for the latest byteseek syntax used for bit fields. I can expedite that work if there is an interest. 

For the processing engine alone, something like the v84 set above should be adequate for inclusion in the DROID unit-test package.

**Comment by snail1966** [comment]
The test suite from Ross is now included in the branch at https://github.com/snail1966/droid/tree/skeletons.  The unit test which runs these will work with any files where the filename starts with the expected PUID (with / replaced by -e.g. fmt-1-myfile.test = fmt/1, and x-fmt-1-myfile.test = x-fmt/1).

**Comment by paulyoung84** [comment]
Fixed in 6.3
