### ISSUE TITLE
fmt/894 skeleton file not matching... 

### ISSUE THREAD

**Issue by ross-spencer** [digital-preservation/droid#115]
I've created this skeleton layout for GJF based on the v88 signature file and it's not matching in DROID, see below screenshot for DROID/Signature File Details:

Bytes:

      414D31
      00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
      0A
      2D31
      20
      35
      00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
      34
      2E
      34
      000000000000000000000000
      34
      2E
      34
      000000000000000000000000
      34
      2E
      34
      23

Sig:

      (414D31|504D33|53544F2D3347|332D323147|332D323167|362D333147|362D333167|6175672D63632D7076747A)
      {0-128}
      0A
      (2D31|30|31)
      (20|2C)
      [31:39]
      {1-128}
      [30:39]
      2E
      [30:39]
      {0-24}
      [30:39]
      2E
      [30:39]
      {0-24}
      [30:39]
      2E
      [30:39]

![image](https://cloud.githubusercontent.com/assets/1880412/18936521/80e17016-8644-11e6-9bcb-541b6e399f99.png)

I had a look at the PRONOM v85 to understand the provenance of this signature and see that since the beginning it has had a (ABCD|1234) style pattern at the beginning of the string. If this issue is verified, could it be because of a lack of a single anchor for the signature?

**Comment by richardlehane** [comment]
your fmt/894 skeleton file fails in sf too, but because of that last hex 23 in your skeleton file that is at the wrong offset, I reported that here: https://github.com/exponential-decay/skeleton-test-suite-generator/issues/5

same issue?

**Comment by ross-spencer** [comment]
It is. Good spotting. I've got to sort out my reading glasses as I read that as EOF not BOF. Skeleton Generator reads signatures in order and I need to put the logic in to order as described by the signatures not the XML output. 

Non-issue for PRONOM/DROID. If I correct the skeleton it matches.
