### ISSUE TITLE
CSV export error - STATUS column entries

### ISSUE THREAD

**Issue by paulyoung84** [digital-preservation/droid#137]
In the CSV export for versions of DROID post 6.1.5 instead of correctly returning a value ‘Access denied’ or 'Not found' when trying to read files without permissions or files which have been moved or deleted in the STATUS column it reports ‘Done’ even though it fails to pick up any identifications.

**Comment by rhubner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#137 CSV export error - STATUS column entries](https://trello.com/c/8f20tRPT/57-137-csv-export-error-status-column-entries)

**Comment by paulyoung84** [comment]
fixed with https://github.com/digital-preservation/droid/commit/bd15380a86351a4be1a40d82c3185cff85bec2c6

**Comment by DavidUnderdown** [comment]
In test
