### ISSUE TITLE
DROID return last accessed date

### ISSUE THREAD

**Issue by paulyoung84** [digital-preservation/droid#139]
Request sent in by Whitmore High School for DROID to be able to return 'last accessed date' as well as 'last modified date'

**Comment by rhubner** [comment]
It's possible but when you run droid on the file it will also change this date.

- 1st run: Last accessed date : 1.1.1970
- 2nd run: Last accessed date : "date of previous run" eg: 1.3.2017

Also most of new don't update last accessed date. In Linux "noatime" option.
