### ISSUE TITLE
Unicode file names on Windows

### ISSUE THREAD

**Issue by schaeferc-si** [digital-preservation/droid#140]
Using droid-command-line-6.2.1.jar (signature V88) on Ubuntu and Windows10.

On Ubuntu, I can get Droid to properly output file names containing Unicode code points. On Windows I can only get output with '?' for each Unicode (presumably utf-16 code point). Is Droid expected to behave properly with unicode file names on Windows?

**Comment by DavidUnderdown** [comment]
Hi this was previously raised in issue #116 - there's a workaround there for 6.2 where you can specify the encoding by invoking at the command line rather than using the supplied .bat.  It was fixed fully in [Droid 6.3](https://github.com/digital-preservation/droid/releases/tag/droid-6.3) released on 3 February.

**Comment by DavidUnderdown** [comment]
Sorry, I misunderstood the issue.  We will do some more investigation, but it may be related to issues in the command window which sometimes uses a different code page.

**Comment by paulyoung84** [comment]
Hi, could you let me know which characters are causing this issue? I am having some issues replicating the problem. Could you also give me some more information about your working environment, e.g java version, systems locale. Thanks

**Comment by schaeferc-si** [comment]
One directory name is 宋冬讲座 . Paths containing this, when output by droid, will appear as .../????/...

I am a once-a-week volunteer at SI Archives; I can't check the Java version until Thrusday. But I think it is Java 1.7. On Ubuntu 16.4, I am running Java 1.8.

Lynda: could you check the Java version; for system locale, see here: https://www.java.com/en/download/help/locale.xml
________________________________

**Comment by schaeferc-si** [comment]
Java version is "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b15, mixed mode)

System locale indicates Current language for non-Unicode programs is English (United States)

Lynda

From: Schaefer, Carl
Sent: Monday, March 27, 2017 2:14 PM
To: digital-preservation/droid <reply@reply.github.com>
Cc: Schmitz Fuhrig, Lynda <SchmitzfuhrigL@si.edu>
Subject: RE: [digital-preservation/droid] Unicode file names on Windows (#140)

One directory name is 宋冬讲座 . Paths containing this, when output by droid, will appear as .../????/...

I am a once-a-week volunteer at SI Archives; I can't check the Java version until Thrusday. But I think it is Java 1.7. On Ubuntu 16.4, I am running Java 1.8.

Lynda: could you check the Java version; for system locale, see here: https://www.java.com/en/download/help/locale.xml
________________________________

**Comment by paulyoung84** [comment]
Hi, could you let me know if you are outputting your results into a csv using -e or if you are reading them in the cmd window?

The default windows character set in cmd line is set to system locale, the European standard code page is 850 and for the US is 437. You can check which one you are using by typing chcp. 

When we run DROID under our default code set the characters appear as question marks in the window but if we export the results to csv (which exports in UTF8) and open this in notepad++ with encoding set to UTF8 it looks like it appears correctly. Would you be able to try this and let us know what behavior you are getting?

**Comment by schaeferc-si** [comment]
I'll check that on Thursday. I'm not sure I've ever run it with the -e option, but I have done a cmd line redirect ('>') to a file.

But the original scenario for using droid was more involved: I was running droid as part of an automated pipeline, written in Python 2.7. The pipeline opens a subprocess pipe as follows:

    p1 = Popen([self.java_path, '-jar', self.droid_path, '--recurse',
        '--signature-file', self.droid_signature, '--no-profile-resource', fn], stdout=PIPE)
    lines = re.split('\n', p1.communicate()[0])
    for line in lines:
      # parse the line...


________________________________

**Comment by schaeferc-si** [comment]
Hi Paul,

Our default code page is 437. When I run the 2-step version of Droid (first create the profile, then create the .csv from the profile), and then view in Notepad, the characters do, indeed, display correctly.

We were trying to build a streamlined process, avoiding where possible the creation of intermediate files. Hence the attempted use of the pipe.

Carl.

**Comment by paulyoung84** [comment]
Carl are you happy for us to close this issue? Thanks

**Comment by schaeferc-si** [comment]
Hi Paul,

If there is no other request for connecting Droid output to a pipe, then I guess you might as well close it.

For the future, you might think about building a simple api that allows a program to initialized droid once, and then call the format id algorithm from within the program, one file at a time. Fido allows this, and I am finding it much more convenient Droid, since my program can get the format id for a single file whose name is already known to the program – gets around the character set conversion issues.

Carl

**Comment by paulyoung84** [comment]
Hi Carl,

Thanks for your reply, we will add you suggestion to our roadmap for consideration for future versions.

Paul
