### ISSUE TITLE
the filter operator not_contains is reported as invalid DQL operator on command line?

### ISSUE THREAD

**Issue by jamesmooneybodleian** [digital-preservation/droid#150]
I've been trying to use not_contains as a filter operator in conjunction with the field file_name.

the operator contains works fine eg:
./droid.sh -p "/data/results/result.droid" -f "file_name contains 'CITATION'" -e "/data/exports/filteredResults.csv"

however the following using non_contains fails:
./droid.sh -p "/data/results/result.droid" -f "file_name not_contains 'CITATION'" -e "/data/exports/filteredResults.csv"

Reporting:
Exception in thread "main" uk.gov.nationalarchives.droid.command.filter.DqlParseException: java.lang.IllegalArgumentException: Invalid DQL operator [not_contains]

Running on Redhat 6.8 with version 6.3 of Droid

**Comment by rhubner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [the filter operator not_contains is reported as invalid DQL operator on command line](https://trello.com/c/e8HV8ST5/76-the-filter-operator-not-contains-is-reported-as-invalid-dql-operator-on-command-line)

**Comment by rhubner** [comment]
Hi,
You put wrong filter keyword. It should be `not contains` with space instant of `not_contains`.

Radek

**Comment by jamesmooneybodleian** [comment]
Ah thanks Radek.
