### ISSUE TITLE
Can you guys make it so that it renames the files it scans?

### ISSUE THREAD

**Issue by jpcreeper13** [digital-preservation/droid#182]

**Comment by Dclipsham** [comment]
Hi there,
On the surface this sounds like undesirable behaviour for a tool primarily used for digital preservation. Can you please describe the use-case?
David

**Comment by jpcreeper13** [comment]
I'm using it to identify "extracted.x" files from a warc file, and I want the program to be able to change the files of the extracted files based on the identification

**Comment by alexgreenDP** [comment]
Did you get a response to your question?

Alex

**Comment by jpcreeper13** [comment]
I never got a reply

**Comment by paulyoung84** [comment]
Hi, I am sorry for the late reply. Unfortunately this is not something which would be in scope for DROID. As a digital preservation tool it is designed to scan the files without causing any changes to them.

**Comment by jpcreeper13** [comment]
I’m trying to get my files back

**Comment by anjackson** [comment]
@jpcreeper13 Are you wanting to get lots of files back, or is it a small enough number that you could do them individually?

If the latter, you could use [WebRecorder Player](https://github.com/webrecorder/webrecorderplayer-electron#webrecorder-player) or if you are on macOS [The Unarchiver](https://theunarchiver.com/) supports WARCs.

**Comment by jpcreeper13** [comment]
It’s a 56 GB archive with around 55,000 files

**Comment by anjackson** [comment]
What format is the archive? Is it WARCs? Or was that just a wild guess too far?

**Comment by jpcreeper13** [comment]
It is a WARC. I’m looking for video files

**Comment by anjackson** [comment]
The best option I know of is [warcat](https://pypi.python.org/pypi/Warcat/), but only if you are happy running tasks from the command line. Once installed, you should be able to use it like this:

    $ python3 -m warcat extract megawarc.warc.gz --output-dir ./extracted/megawarc/ --progress

If you need a GUI then The Unarchiver is the only one I know of, and that's macOS-only.
