### ISSUE TITLE
Ability to cherry pick types of archival container to be scanned

### ISSUE THREAD

**Issue by Dclipsham** [digital-preservation/droid#184]
It would be beneficial to pick and choose which archival containers DROID should scan. For example I may wish to look inside zips but not iso images. 

I'd envisage some kind of checkbox option system allowing you to tick all the containers one would like to scan, along with a 'select all/select none' option to clear/populate all checkboxes.

**Comment by jcharlet** [comment]
@Dclipsham for GUI, is that satisfying ?

https://docs.google.com/drawings/d/1u_zC_oReeD9KLJGqeGovz6rwXr6b_IZphyYmk6XeyHA/edit?usp=sharing

![image](https://user-images.githubusercontent.com/1750370/67807922-a198f700-fa8d-11e9-92ae-5bed4dd5e025.png)
