### ISSUE TITLE
Status of Java 9 support?

### ISSUE THREAD

**Issue by ross-spencer** [digital-preservation/droid#186]
See https://groups.google.com/d/msg/droid-list/0Ljhu1jXKdk/oCEnlQOdBQAJ - there's a chance Java 9 does not currently play well with DROID.

**Comment by adamretter** [comment]
I just added support for Java 9 here - https://github.com/digital-preservation/droid/pull/188

**Comment by alexgreenDP** [comment]
Thanks for the Java 9 support. We have decided not to officially support Java 9 or Java 18.3 but will be working towards support for Java 18.9.

**Comment by adamretter** [comment]
@alexgreenDP Could you spare a second to talk about this? My change, makes sure that DROID both works on Java 8 (as it currently does), and also works on Java 9 (which it didn't before).

I don't see any downside to adding support for Java 9. You don't loose anything AFAIK. A couple of points:

1. The default download when installing Java, has been Java 9 for some time now.
2. Java 8 will be End-of-Life in Sept 2018.
3. The absolute earliest that Java 18.9 will be available is Sept 2018. So it seems you may have a period when DROID does not run on a supported (by Oracle) version of Java.
4. The changes that I have made for Java 9, will likely be required to get to Java 18.3 or 18.9. Incremental steps will make moving forward easier.

Happy to discuss by phone if that is easier...

**Comment by rhubner** [comment]
Hi Adam,

don't worry, Your pull request will be merged. We just don't have enough resources to fully support Java9. I will do the best to support it. What I seen, they changed lot of stuff and lot of externals libraries don't support java 9 yet.

I already identified some parts of DROID which need rewrite for next java releases. Some APIs which are marked to be removed in next version. 

EOL of java 8 - I probably misinterpreted previously Oracle road map. This change everything around support. Thanks for the point.

Radek
