### ISSUE TITLE
Incompatible db format on profile initialisation on latest master

### ISSUE THREAD

**Issue by nishihatapalmer** [digital-preservation/droid#194]
Hi,

**Problem**
I just got the latest changes in master and built droid.  It fails to initialise the profile, as the db format is incompatible. 
```
Caused by: java.sql.SQLException: Database at /home/matt/.droid6/profiles/1511809544781/db has an incompatible format with the current version of the software.  The database was created by or upgraded by version 10.12.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
```

**Workaround**
 I got rid of my .droid6 folder and it then ran fine. 

**Solution?**
 I guess the derby database has been updated and is incompatible with the old db formats.  I know droid has a mechanism to cache db formats to save time on profile initialisation - it seems like it needs a template for the new version of derby.

**Comment by nishihatapalmer** [comment]
If you look in DroidGlobalConfig.java, in core-interfaces, there are these lines:

```
    // UPDATE THIS SCHEMA VERSION IF THE DATABASE SCHEMA CHANGES.
    private static final String TEMPLATE_SCHEMA_VERSION = "schema 6.04";
```

From memory, this is how you define an incompatible new database format.  You create a new schema version and update the version here.  I think this forces droid to generate a new blank template, but I haven't tested it.

**Comment by nishihatapalmer** [comment]
OK, I tested it, and it works.  I restored the old non working .droid6 folder and verified I got the same error I got.  Then I updated the version string to "**schema 6.5**", rebuilt and ran.  All worked fine, and DROID created a new schema 6.5 subfolder with a new db profile.template file, under the .droid6/profile_templates folder.

So I guess that is the fix...

**Comment by nishihatapalmer** [comment]
A final thought - it was originally intended to make DROID compatible with possible future schema changes, but it's clearly also capable of guarding against incompatible database format upgrades in derby.

Maybe it should be called something more general like SUPPORTED_DATABASE_VERSION instead?

**Comment by rhubner** [comment]
Hi,

thanks for bugreport. I can replicate same behaviour on my machine. It looks that DERBY DB have only forward compatibility. 

Radek

**Comment by Dclipsham** [comment]
wontfix
