### ISSUE TITLE
PRONOM records not updating after being edited

### ISSUE THREAD

**Issue by ross-spencer** [digital-preservation/droid#196]
E.g. fmt/134. In PRONOM is recorded as being modified in 2005 but it was last updated in November 2017 in DROID_SignatureFile_V93.xml. As per the [release notes](https://www.nationalarchives.gov.uk/aboutapps/pronom/release-notes.xml) 

![image](https://user-images.githubusercontent.com/1880412/36333323-f4f9acba-132a-11e8-9263-987067c2dacd.png)

One impact of this is that it is not always straightforward to track a change in identification result down without making sure both sources of dates are checked. 

I recognise that this is a legacy/process issue, so perhaps this ticket can be logged as a future enhancement request.

**Comment by Dclipsham** [comment]
Thanks Ross, yes that's fair - it's a manual field to update in the database so often gets missed. I'll see if we can automate it, or at least update our release procedures.

**Comment by Dclipsham** [comment]
PRONOM process issue. Closing here.
