### ISSUE TITLE
Localisation problem in number format make mvn install fail

### ISSUE THREAD

**Issue by JSLair** [digital-preservation/droid#197]
In droid-result, the FileUtilTest is used to test file size formatting. It failed during install on my "French" system. 
I found that it's a problem of number formatting. In France the thousands separator is a space, and in UK it's a comma. With the following FileUtilTest.java it's OK on my system:

package uk.gov.nationalarchives.droid.util;

import static org.junit.Assert.assertEquals;
import java.text.DecimalFormatSymbols;

import org.junit.Test;

/**
 * @author rflitcroft
 *
 */
public class FileUtilTest {

    @Test
    public void testFormatFileSize() {
        
        final long kb12 = 12L * 1024L;
        final long mb12 = 12L * 1000L * 1024L;
        final long gb12 = 12L * 1024L * 1024L * 1024L;
        final long tb12 = 12L * 1024L * 1024L * 1024L * 1024L;
        
        DecimalFormatSymbols dfs=new DecimalFormatSymbols();
      
        assertEquals("12 bytes", FileUtil.formatFileSize(12L, 3));
        assertEquals("12 KB", FileUtil.formatFileSize(kb12, 3));
        assertEquals("11"+dfs.getDecimalSeparator()+"7 MB", FileUtil.formatFileSize(mb12, 1));
        assertEquals("12 GB", FileUtil.formatFileSize(gb12, 3));
        assertEquals("12"+dfs.getGroupingSeparator()+"288 GB", FileUtil.formatFileSize(tb12, 3));
    }
}

**Comment by alexgreenDP** [comment]
Thank you for your report. We will investigate and find the best way to resolve this.

**Comment by alexgreenDP** [comment]
See #198 for reply.
