### ISSUE TITLE
Another localisation problem make mvn install fail

### ISSUE THREAD

**Issue by JSLair** [digital-preservation/droid#198]
In /droid/droid-swing-ui/src/test/java/uk/gov/nationalarchives/droid/gui/filechooser/ResourceFileChooserTest.java
the line:
 assertEquals("All Files", fc.getFileFilter().getDescription());
can only be OK in english configuration. Could you comment it?

After this second correction, the complete mvn install is OK on my French system.

**Comment by alexgreenDP** [comment]
Thank you for your comment. We will add this to our backlog for prioritisation.  We are likely to add a default locale as solution for this issue.

**Comment by jcharlet** [comment]
fixed in merged PR from @JSLair with commit:
d2e7696ea8ca0f4b38d9650782ae4773fc84da4a "Fix: test not convenient when building in non english environment"

I managed to mvn package the whole project with French locale.
