### ISSUE TITLE
Ability to drag and drop files into DROID (inc Mac)

### ISSUE THREAD

**Issue by ghost** [digital-preservation/droid#204]
This feedback was given to me by one of our Mac users- kp.

**Comment by nishihatapalmer** [comment]
I've submitted a PR that enables file drag drop - not yet tested on Mac or Windows.

**Comment by jcharlet** [comment]
merged PR after testing it on linux. will test it on windows too asap.
can someone test it on mac if I provide binaries?

**Comment by LauraDamianTNA** [comment]
I'll test it on Mac now.

**Comment by LauraDamianTNA** [comment]
It works fine on Mac OS X Yosemite.
