### ISSUE TITLE
Ability to add a DROID shortcut to the dock/ icon toolbar on a Mac

### ISSUE THREAD

**Issue by ghost** [digital-preservation/droid#205]
This feedback was given to me by one of our Mac users. kp.

**Comment by Dclipsham** [comment]
wontfix

**Comment by Dclipsham** [comment]
we're considering packaging application for windows & mac etc which may resolve this issue, but we can't prioritise this issue specifically

**Comment by adamretter** [comment]
@Dclipsham If you want a Mac DMG, then I maintain some tools for that process, including - https://github.com/evolvedbinary/appbundler-maven-plugin
