### ISSUE TITLE
droid CLI gives empty CSV report

### ISSUE THREAD

**Issue by nvanderperren** [digital-preservation/droid#208]
I'm trying to use Droid CLI. This command gives me an empty csv-report. 

`./droid.sh -p "/Users/nastasia/Desktop/test.droid" -e "/Users/nastasia/Desktop/test.csv"`. I also tried the `-r` option, but that gives me the same result

Output of the report:
`"ID","PARENT_ID","URI","FILE_PATH","NAME","METHOD","STATUS","SIZE","TYPE","EXT","LAST_MODIFIED","EXTENSION_MISMATCH","HASH","FORMAT_COUNT","PUID","MIME_TYPE","FORMAT_NAME","FORMAT_VERSION"`

Am I doing something wrong? I don't see a difference with the examples of the documentation.

**Comment by rhubner** [comment]
Hello @nvanderperren, 

I'm not able to replicate your bug. It's possible to send us `test.droid` file.If not, can you check with GUI version of DROID which identifications you have in profile. It looks that your profile is empty.
Radek

**Comment by Dclipsham** [comment]
cannot replicate therefore cannot investigate without further information. Happy to reopen if provided
