### ISSUE TITLE
Minor addition to the DROID GUI guidance proposed

### ISSUE THREAD

**Issue by ghost** [digital-preservation/droid#209]
A regular user has suggested that we add the note below to the GUi guidance of DROID. Adding it here so that it's flagged at the next meeting. KP.

/////////////

To control DROID on the command line it is necessary to execute DROID first and then in a second terminal window to navigate to the folder where DROID is installed in order to run commands.

Note for Linux users

These instructions are based on the Windows command line. Users of DROID on the Linux shell should substitute
	./droid.sh
for the Windows command
	droid
It may be necessary to add execute permissions to the droid.sh file to enable this.

Users must specify the full path of folders and files. For example
	./droid.sh -a “../../Documents/A Folder” -p “../../Documents/Results/
	Result1.droid”

**Comment by nishihatapalmer** [comment]
I don't understand this issue.  You can't add commands to an already running DROID from a second terminal.

If it just means that when you run DROID from a command line, the existing terminal is unavailable for further commands until it exits, this is just standard terminal behaviour, and not peculiar to DROID in any way.

I guess if it causes confusion some guidance could be added though.

**Comment by jcharlet** [comment]
@Dclipsham shall we close that issue?

**Comment by Dclipsham** [comment]
In principle yes, but let's review the original email request first - we can reach out to the user to understand the issue better.

**Comment by jcharlet** [comment]
do you have the email @Dclipsham ? The author's account for this github issue is removed.

**Comment by jcharlet** [comment]
didn't find on droid and pronom groups
