### ISSUE TITLE
`droid -d` CLI command results in corrupt container sig file 

### ISSUE THREAD

**Issue by richardlehane** [digital-preservation/droid#217]
Hi droid team
since the PRONOM v94 update I've been trying to re-run my benchmarks (https://www.itforarchivists.com/siegfried/benchmarks) but can't get a scripted signature update working for DROID using the `droid -d` command. Weirdly it seems to work when I login to the server and run the command interactively but when I try to script it as part of the server config (https://github.com/richardlehane/provisioner/blob/master/scripts/bench.yaml), I end up with a container signature file with three invalid characters at the start:

![image](https://user-images.githubusercontent.com/157422/45800598-bdf82b00-bcf4-11e8-9b20-14c058a12ca6.png)

When I subsequently run droid I get this error:

uk.gov.nationalarchives.droid.core.SignatureParseExceptionuk.gov.nationalarchives.droid.container.ContainerSignatureSaxParser.parse(ContainerSignatureSaxParser.java:73
uk.gov.nationalarchives.droid.container.AbstractContainerIdentifier.init(AbstractContainerIdentifier.java:175)\n\t... 24 more\nCaused by: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

Perhaps this is related to the whitespace issue with the container signature file?
thanks
Richard

**Comment by Dclipsham** [comment]
Thanks Richard,

I see an errant UTF-8 byte order mark, likely introduced in error by one of the text editors we use. I've released container signature 20180920 which removes the BOM and hopefully resolves this issue too. Let me know if not.

David

**Comment by richardlehane** [comment]
Hi @Dclipsham  thanks the fresh container release has fixed this issue too
cheers
Richard
