### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by JSLair** [digital-preservation/droid#227]
We need to use Droid in a production but with a fix currently in 6.5-SNAPSHOT.
When do you intend to publish a new 6.5 release?

**Comment by jcharlet** [comment]
hi @JSLair , sorry for the late reply, will be released in the beginning of next year, hopefully, early Jan.

**Comment by jcharlet** [comment]
FYI, we did a first round of testing for 6.5 release. are now fixing bugs, adding small missing features and will release asap in the following weeks.
