### ISSUE TITLE
RequestMetaData's size parameter

### ISSUE THREAD

**Issue by krt16s** [digital-preservation/droid#230]
I post here, since "Bug-fixes, feature requests, and **code support** should be raised through our GitHub issues page". If the mailinglist is more applicable, please sa so.

I tried invoking Droid 6.4 from a Java program and I am not sure if I am doing it correctly. Especially I am not sure what RequestMetaData's size parameter is supposed to do. I think it should be set to `file.length()` but this breaks the identification of a DOCX document, written by LibreOffice (docx_libreoffice.docx in my repo).

- my code: https://github.com/krt16s/droiddebug/blob/master/src/main/java/App.java
- my test file: https://github.com/krt16s/droiddebug/blob/master/docx_libreoffice.docx
- my results (sizelimit is the value set in the request):

````
MEMINFO: 3784310784 max, 178968528 free, 590348288 total, 4155 sizelimit, 4155 filesize
INFO: request != null
RESULT: droid-mimetype:application/zip, droid-typename:ZIP Format, droid-puid:x-fmt/263, droid-x-version:null, droid-x-extid:null
INFO: remove lower hits
RESULT: droid-mimetype:application/zip, droid-typename:ZIP Format, droid-puid:x-fmt/263, droid-x-version:null, droid-x-extid:null
MEMINFO: 3784310784 max, 228719128 free, 555745280 total, 4155 sizelimit, 4155 filesize
---
MEMINFO: 3784310784 max, 228719128 free, 555745280 total, 3155 sizelimit, 4155 filesize
INFO: request != null
INFO: .size() == 0
RESULT: droid-mimetype:application/vnd.openxmlformats-officedocument.wordprocessingml.document, droid-typename:Microsoft Word for Windows, droid-puid:fmt/412, droid-x-version:2007 onwards, droid-x-extid:null
RESULT: droid-mimetype:, droid-typename:Microsoft Office Encrypted Document, droid-puid:fmt/494, droid-x-version:2007 Onwards, droid-x-extid:null
INFO: remove lower hits
RESULT: droid-mimetype:application/vnd.openxmlformats-officedocument.wordprocessingml.document, droid-typename:Microsoft Word for Windows, droid-puid:fmt/412, droid-x-version:2007 onwards, droid-x-extid:null
RESULT: droid-mimetype:, droid-typename:Microsoft Office Encrypted Document, droid-puid:fmt/494, droid-x-version:2007 Onwards, droid-x-extid:null
MEMINFO: 3784310784 max, 210138952 free, 524812288 total, 3155 sizelimit, 4155 filesize
````

**Comment by nishihatapalmer** [comment]
The RequestMetadata size parameter is the size in bytes of the data to be processed.  So in your code, it should be the filesize you obtain in this code:

            long filesize = new File(args[1]).length();

Your code then has various loops that pass in completely different values to filesize,  so I'm not surprised it breaks.

**Comment by nishihatapalmer** [comment]
If you want to limit how much of a file is processed in order to identify it, you need to call setMaxBytesToScan() on the BinarySignatureIdentifier.  Passing in -1 to this will make DROID run a full file scan.

**Comment by krt16s** [comment]
Thanks for your response.

The loops are for playing around if you just use `filesize` the results are
not correct (well, not specific enough):

````
long filesize = new File(args[1]).length();
doDroidIdent(args[0], args[1], filesize);
````

````
RESULT: droid-mimetype:application/zip, droid-typename:ZIP Format,
droid-puid:x-fmt/263, droid-x-version:null, droid-x-extid:null
````

**Comment by Dclipsham** [comment]
closing as per Matt's response. Please reopen if you feel this isn't resoved

**Comment by krt16s** [comment]
I updated the sample code. The [docx file created with libreoffice](https://github.com/krt16s/droiddebug/blob/master/docx_libreoffice.docx) is still only recognized as a generic zip file:

````
$ ./build/install/droidsample/bin/droidsample DROID_SignatureFile_V96.xml docx_libreoffice.docx  2> /dev/null
INFO: request != null
RESULT: droid-mimetype:application/zip, droid-typename:ZIP Format, droid-puid:x-fmt/263, droid-x-version:null, droid-x-extid:null
INFO: remove lower hits
RESULT: droid-mimetype:application/zip, droid-typename:ZIP Format, droid-puid:x-fmt/263, droid-x-version:null, droid-x-extid:null
MEMINFO: 4257218560 max, 130804352 free, 266338304 total, 4155 size, 4155 filesize
````

A [docx created in MS word](https://github.com/krt16s/droiddebug/blob/master/docx_msword.docx) shows the correct response:

````
$ ./build/install/droidsample/bin/droidsample DROID_SignatureFile_V96.xml docx_msword.docx  2> /dev/null
INFO: request != null
RESULT: droid-mimetype:, droid-typename:Microsoft Office Open XML, droid-puid:fmt/189, droid-x-version:2007 onwards, droid-x-extid:null
RESULT: droid-mimetype:application/zip, droid-typename:ZIP Format, droid-puid:x-fmt/263, droid-x-version:null, droid-x-extid:null
INFO: remove lower hits
RESULT: droid-mimetype:, droid-typename:Microsoft Office Open XML, droid-puid:fmt/189, droid-x-version:2007 onwards, droid-x-extid:null
MEMINFO: 4257218560 max, 130021152 free, 266338304 total, 11852 size, 11852 filesize
````
