### ISSUE TITLE
Question: can Droid scan a database

### ISSUE THREAD

**Issue by Nescu** [digital-preservation/droid#233]
Hello, 
I've seen that I could use Droid to identify duplicate, can it scan a database? I'm trying to identify duplicates in a records management system database. I've only used it on shared drives so far. 

Thank you

**Comment by Dclipsham** [comment]
Hello Nescu,

Currently DROID can only scan the hierarchy of file systems it is allowed and able to navigate, so it is unlikely to be able to navigate a records management system database unless its hierarchy can be exposed in some way, e.g. as a mountable file share. Can I ask which records management system you are using?

David
