### ISSUE TITLE
Question on java requirement

### ISSUE THREAD

**Issue by oschihin** [digital-preservation/droid#284]
System requirements for DROID are ["Java 8 Standard Edition (SE)"][1]. Are there any experiences and / or recommendations regarding openjdk, also LTS version 8 and 11?

[1]: http://digital-preservation.github.io/droid/

**Comment by ross-spencer** [comment]
@oschihin for convenience I'm using the following when I use DROID:
```
$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```
It works. The impact to me is that if I see something wrong while using the tool, I have to verify the same issue on Java 8 SE from Oracle before reporting it, i..e the supported version. OpenJDK is a variable in itself which needs to be controlled. If something happens to be wrong with DROID it might just be in OpenJDK's support for a specific feature.

**Comment by oschihin** [comment]
@ross-spencer thanks for the quick response. We're running DROID on a Windows Server as part of a lager ingesting infrastructure. So it is not straightforward to double-check. Background is Oracles licensing policy for Java SE, recommending openjdk if you do not subscribe.

**Comment by Dclipsham** [comment]
Hi, Issue #283 covers current work on this. We're actively developing right now and targeting openjdk11 for the next release 6.5, and we're looking at bundling the runtime with the binaries.

**Comment by oschihin** [comment]
Thanks. This is interesting, looking forward to 6.5.
I'll close here

**Comment by adamretter** [comment]
Apart from the builds on JDK 8. It is worth maybe also worth mentioning that DROID is tested on OpenJDK 8, 9, 10 and 11 automatically via Travis CI - https://travis-ci.org/digital-preservation/droid/builds/592087473
