### ISSUE TITLE
Specify ContainerSignature ByteSequence Reference offsets explicitly.

### ISSUE THREAD

**Issue by nishihatapalmer** [digital-preservation/droid#313]
There are quite a lot of container signatures that don't specify the Reference attribute of the ByteSequence element (BOFOffset, EOFOffset or Variable).

By convention, if it isn't specified it defaults to Variable (there are some binary signatures that seem to do this).

But I don't think all of these container signatures should be variable.  I think they should actually be BOFOffset.  In any case, it would be better to be explicit, by providing Reference attribute values for the ByteSequences.

For example, this signature specifies it should scan from 0 to 4096.  I think that means it's actually a BOFOffset, as if it were variable the min/max offsets are ignored and the entire buffer is scanned (up to any max limits DROID imposes).

```
<ContainerSignature Id="1070" ContainerType="ZIP">
      <Description>Microsoft Word OOXML Template</Description>
      <Files>
        <File>
          <Path>[Content_Types].xml</Path>
          <BinarySignatures>
            <InternalSignatureCollection>
              <InternalSignature ID="1070">
                <ByteSequence>
                  <SubSequence Position="1" SubSeqMinOffset="0"
                    SubSeqMaxOffset="4096">
                    <Sequence>'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.template.main+xml"'</Sequence>
                  </SubSequence>
                </ByteSequence>
              </InternalSignature>
            </InternalSignatureCollection>
          </BinarySignatures>
        </File>
      </Files>
    </ContainerSignature>
```

**Comment by nishihatapalmer** [comment]
So the fixed version should read:
```
<ContainerSignature Id="1070" ContainerType="ZIP">
      <Description>Microsoft Word OOXML Template</Description>
      <Files>
        <File>
          <Path>[Content_Types].xml</Path>
          <BinarySignatures>
            <InternalSignatureCollection>
              <InternalSignature ID="1070">
                <ByteSequence Reference="BOFoffset">
                  <SubSequence Position="1" SubSeqMinOffset="0"
                    SubSeqMaxOffset="4096">
                    <Sequence>'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.template.main+xml"'</Sequence>
                  </SubSequence>
                </ByteSequence>
              </InternalSignature>
            </InternalSignatureCollection>
          </BinarySignatures>
        </File>
      </Files>
    </ContainerSignature>
```

**Comment by nishihatapalmer** [comment]
When container signatures are compiled in DROID (like any signatures), they issue a warning if they are a variable sequence (it may not be wrong, but it imposes a high performance penalty, so we don't want to do this by mistake).  In this case, I believe the warning has helped catch signatures which should not be variable, and should be BOFoffset.

I can't see why a variable signature would specify subseqmin - subseqmax offsets, as they will just be ignored.  Much more likely that someone forgot to put "BOFoffset" as the Reference attribute...

**Comment by nishihatapalmer** [comment]
Could modify the warning code to only warn on signatures with subsequence offsets which are ignored by the variable reference.

**Comment by nishihatapalmer** [comment]
The warning code is in InternalSignature:

```java
private boolean prepareByteSequences() {
        final int endIndex = byteSequences.size();
        boolean hasOnlyVarSequences = true;
        for (int byteSequenceIndex = 0; byteSequenceIndex < endIndex; byteSequenceIndex++) {
            ByteSequence byteSequence = byteSequences.get(byteSequenceIndex); 
            byteSequence.prepareForUse();
            if (byteSequence.isInvalidByteSequence()) {
                return true;
            }
            if (byteSequence.isAnchoredToBOF() || byteSequence.isAnchoredToEOF()) {
                hasOnlyVarSequences = false;
            }
        }
        if (hasOnlyVarSequences) {
            getLog().warn(getPerformanceWarningMessage());
        }
        // must call reorderByteSequences after first preparing byte sequences for use
        // as it relies on their sort orders defined when preparing them for use.
        reorderByteSequences();
        calculateSignatureSortOrder();
        return false;
    }
```

**Comment by Dclipsham** [comment]
see also #98

**Comment by Dclipsham** [comment]
Currently all container signature sequences are intended as relative to BOF so I think the warning essage is appropriate. Fix is to make the offsets explicit

**Comment by jcharlet** [comment]
this will be directly fixed in PRONOM on the signatures raising that warning. The BOF should be explicitly defined in the first place, and DROID is doing his job about warning it. Closing the issue.
