### ISSUE TITLE
DROID objects extremely hard to instantiate

### ISSUE THREAD

**Issue by nishihatapalmer** [digital-preservation/droid#329]
There are a lot of DROID objects which are impossible to instantiate with Java, unless you use a dependency injection system like Spring.  They have private members and no programmatic way to set them.

Other classes can be instantiated, but then require multiple setters running to ensure that the object is in a safe state.  There is no indication what needs to be set on these classes, and what's optional.

It would be good if DROID objects could be instantiated using systems like Spring and also in a normal programmatic way via a constructor.

**Comment by nishihatapalmer** [comment]
This has no effect on users of course; it just makes working with DROID code unnecessarily hard, and ties the code to Spring.

**Comment by nishihatapalmer** [comment]
I am working on a PR which adds both empty constructors (for Spring like systems), and parameterized constructors to allow the objects to be constructed normally.

There's a lot of them, but the changes are minimal (adding two constructors to each affected object).  It should have no effect on the current running of DROID, because we are only adding constructors that nothing currently calls.

**Comment by adamretter** [comment]
In general the data objects should be designed as POJOs (i.e. Java Beans), in this manner they can be instantiated either with or without Spring.

**Comment by nishihatapalmer** [comment]
Unfortunately, quite a few of them aren't POJOs at all (no way to instantiate without Spring).  

The other ones which require multiple setters calling to ensure the object is safe to use are technically POJOs, but are hard to use safely.
