### ISSUE TITLE
-Nr no-profile mode doesn't use default signature

### ISSUE THREAD

**Issue by mistydemeo** [digital-preservation/droid#33]
Even if the user has selected a default signature file to use, the `-Nr` no-profile mode won't use it and requires the full path to the XML file to be specified. This is unlike the behaviour for the profile mode, where the default file is used if one has been selected.

```
$ droid -x 2>/dev/null
Type: Container Version:  20130501  File name: container-signature-20130501.xml
Type: Binary Version:  69  File name: DROID_SignatureFile_V69.xml

$ droid -Nr path/to/file
No signature file specified.
```

**Comment by mpbraendle** [comment]
OK, that answer was two years ago.

**Comment by DavidUnderdown** [comment]
This was a deliberate decision to avoid the no profile mode having to access any configuration file.  We will review this in future, but it's unlikely to change in the short term
