### ISSUE TITLE
Unable to select any option other than UTF-8 for encoding in the 'Export profiles' dialog

### ISSUE THREAD

**Issue by sparkhi** [digital-preservation/droid#386]
Steps to reproduce

1. Launch Droid, select a folder and start profiling 
2. Once the profiling has finished, click on the export button 
3. Am 'Export profiles' diloag appears.
4. Select the profile to export 
5. In the 'Encoding' dropdown, try to select anything other than UTF 8 
------ BUG: You cannot select any other option for the encoding

**Comment by Dclipsham** [comment]
Seems okay in my environment (Win 10, DROID 6.4) 
![image](https://user-images.githubusercontent.com/2189778/74832723-ce5c6d00-530f-11ea-86c9-27e0c08007cf.png)
Is this a regression or platform-specific?

**Comment by sparkhi** [comment]
The dropdown appears and I could highlight the other options similar to your screenshot, however I could not actually select any other option

**Comment by Dclipsham** [comment]
curious. It allowed me to export and didn't complain further. My export of UTF-8 with BOM did include the BOM

**Comment by sparkhi** [comment]
Looks like it. I just tried on Droid 6.4 and it worked for me, It exported with UTF-8 BOM

**Comment by jcharlet** [comment]
My bad, don't understand why my own build of droid 6.4 on linux failed with
the same error, though I removed .droid6 folder.
ᐧ

**Comment by Dclipsham** [comment]
is certainly occurring in DROID 6.5 RC1 Win10

**Comment by sparkhi** [comment]
I did some replace-one-item-and-see-what-breaks debugging and I think I know why @jcharlet saw the problem in 6.4 as well.
1) Droid 6.5 RC1 on W10 - Bug
2) Droid 6.4 on W10 - Works fine
3) Droid 6.5 on W10 ran using a JRE which was already installed - Works fine 
4) Dev env on CentOS (using Open JDK 8) - Works fine
5) Dev env on CentOS (using Open JDK 11) - Bug

Basically we are hitting an NPE in JRE 11 and the bundled version of Droid 6.5 has JRE 11 hence the problem with 6.5

**Comment by jcharlet** [comment]
Ah so David gotta be using java 8 for 6.4 while I was using java 11.

We need to define in the plan test to separate os between bundled version
and unbundled on java 8 and java 11

**Comment by jcharlet** [comment]
reproduced: works fine on openjdk 8 locally on 6.5, NPE on openjdk 11 on 6.5

**Comment by jcharlet** [comment]
@Dclipsham I could fix the NPE on 6.5 but I have a problem coming after, that I reproduced as well on 6.4 with openjdk 1.8.

When asking for utf8 with bom, It creates the file as expected, but then it gets stuck on this exporting profiles screen that I cannot close.

Can you reproduce it as well on 6.4 on windows?

![Screenshot from 2020-02-20 15-09-29](https://user-images.githubusercontent.com/1750370/74936797-79922280-53f3-11ea-979f-e6251e56a694.png)

**Comment by jcharlet** [comment]
ah might something else, again. 
Try to export twice, first to bom, then to utf8

**Comment by jcharlet** [comment]
ok happens randomly when doing very small exports. race condition between initialisation of the progress dialog and its closing.
