### ISSUE TITLE
CLI, when running in non-recursive mode, picks up folders which subsequently fail

### ISSUE THREAD

**Issue by sparkhi** [digital-preservation/droid#410]
### Description:
When you run the CLI on a folder which contains subfolders, setting recursive to false, droid still tries to open folders and subsequently fails.
On Windows as well as Linux. it throws a FileNotFound exception

### Acceptance Tests:
- Create a folder called 'issue-410' 
- Under this folder create another folder as well as a text file called 'one.txt'
- On droid use CLI as `droid -Nr /issue-410 -Ns <path-to-signature-file.xml>`
- The result should not produce exception
- The result should produce identification details for 'one.txt' created in step 2 

### Acceptance Tests:
- Create a folder called 'issue-410' 
- Under this folder create another folder called 'subfolder' as well as a file called 'one.txt'
- Under the folder 'subfolder' create a text file called 'two.txt'
- On droid use CLI as `droid -R -Nr /issue-410 -Ns <path-to-signature-file.xml>`
- The result should not produce exception
- The result should produce identification details for 2 files 'one.txt' and 'two.txt' created in step 2 and 3 respectively

**Comment by jcharlet** [comment]
error from @paulyoung84 on windows and linux

![image (4)](https://user-images.githubusercontent.com/1750370/76435820-6a2d4600-63af-11ea-929e-033ab5332fad.png)
![image (3)](https://user-images.githubusercontent.com/1750370/76435825-6ac5dc80-63af-11ea-8f88-4621192f7eb1.png)
