### ISSUE TITLE
fmt-1196 SIARD 2.1 is wrongly identified as ZIP

### ISSUE THREAD

**Issue by sparkhi** [digital-preservation/droid#418]
Getting an identification error with skeleton suite, fmt-1196 SIARD 2.1 is identifying as a ZIP file - x-fmt/263. Getting this in cmd line and gui for Raspbian and win 10 jre version. 6.4 is identifying correctly. Tested on actual SIARD file from https://github.com/sfa-siard/SiardGui/blob/master/testfiles/sql2008.siard as well and got same behavior.

**Comment by ross-spencer** [comment]
Hi @sparkhi just trying to parse this, is the skeleton suite the only one not identifying correctly, or `sql2008.siard` as well? There was a SIARD related issue in the Skeleton generation, documented a little [here](https://github.com/exponential-decay/skeleton-container-test-suite-generator/issues/8#issuecomment-578369692) but should be updated and available in the most [recent suite](https://github.com/exponential-decay/pronom-archive-and-skeleton-test-suite/releases/tag/skeleton-test-suite-2020-01-20-sig-file-v96). This is marked pre-release as I haven't posted it to Zenodo yet.

**Comment by sparkhi** [comment]
Hi @ross-spencer I had created the issue as seen by @paulyoung84 I'm in the process of finding more details. Thanks for the prompt comment, I'll try and locate it.

**Comment by sparkhi** [comment]
Okay, done few more tests. 
1) Droid 6.4 vanilla - identified it as ZIP
2) Did the signature updates on Droid 6.4 and tried - It is identified as SIARD 2.1 
3) Ran Droid 6.5 with the signatures from step 2, identified as ZIP 

So I suspect the issue is in Droid 6.5 code

**Comment by ross-spencer** [comment]
Okay, thanks @sparkhi!
