### ISSUE TITLE
profiles produced now have Windows ends (CR+Newline) rather than just Unix (Newline) 

### ISSUE THREAD

**Issue by Dclipsham** [digital-preservation/droid#440]
Reported via external testing - is causing issues where DROID is chained with other scripts handling DROID's output

**Comment by DavidUnderdown** [comment]
Tricky one - strictly speaking Windows endings are specified by RFC 4180 so we are now producing better CSV files than we were previously

**Comment by adamretter** [comment]
Where in doubt, stick to the specs ;-)

**Comment by Dclipsham** [comment]
not keen on unplanned behaviour changes though, particularly when they have the potential to break things downstream. Would be more comfortable with introducing a preference toggle.

**Comment by adamretter** [comment]
@Dclipsham Or... you could switch DROID to [Semantic Versioning](https://semver.org) and then you could make such a change in a Major version/

**Comment by jcharlet** [comment]
So what should we do here as a fix on 6.5 for @Dclipsham ? Simply put back previous Unix ends? Where is that happening, how to reproduce exactly (export / save profile / GUI / CLI ?)

**Comment by jcharlet** [comment]
as part of unix scripts on windows machine

**Comment by jcharlet** [comment]
check on 6.4 vs 6.5 on Linux and windows 
if regression since 6.4, need to understand what causes it and possibly needs to add toggle to choose output format (windows with CR OR Unix)

**Comment by Dclipsham** [comment]
I'm proposing to revert to existing behaviour (LF only) for DROID 6.5, and putting future change to community for consideration - https://groups.google.com/forum/#!topic/droid-list/CX2ZcyS64xQ
