### ISSUE TITLE
Create / Move to an AppVeyor Organisation

### ISSUE THREAD

**Issue by adamretter** [digital-preservation/droid#445]
At the moment the AppVeyor builds for DROID are performed under my personal account, see - https://ci.appveyor.com/project/AdamRetter/droid. That was fine when we started out, but my account is now getting a bit loaded up!

Would Digital Preservation be able to create an organisation for themselves on AppVeyor please, and move the Droid builds from my account to that org?
 
Cheers. Adam.

**Comment by jcharlet** [comment]
@Dclipsham is waiting for github to recover our digital archiving account.
