### ISSUE TITLE
PDF file containing an image wrongly identified as MP3

### ISSUE THREAD

**Issue by antoineribes** [digital-preservation/droid#463]
Running identification with DROID v6.5 on the file 
[mantis0028948.pdf](https://github.com/digital-preservation/droid/files/4718841/mantis0028948.pdf) results in multiple identifications  	"fmt/134" and "fmt/18" ("MPEG 1/2 Audio Layer 3" and "Acrobat PDF 1.4 - Portable Document Format - version 1.4") as shown in the export 
[mantis0028948.droidreport.csv](https://github.com/digital-preservation/droid/files/4718861/mantis0028948.droidreport.csv.txt).

With Unix File, this file is correctly identified as "PDF document, version 1.4".

Using the Java API (version 6.5 of droid-core and droid-core-interfaces), the IdentificationResult with the wrong format "fmt/134" appears first (at index 0) in the result list, hence before the correct format "fmt/18" which is given in second and last position (index 1).

Note : the - scanned - image of the original PDF that triggered this error could not be shared publicly so the part of the image stream that does not induce the identification problem was cleared.

**Comment by Dclipsham** [comment]
PRONOM prioritisation issue

**Comment by oskarhek** [comment]
Is this issue going to be fixed?

**Comment by Dclipsham** [comment]
Hi, yes the next PRONOM update will include prioritisation of PDF formats over MP3. I don't currently have a firm release date for this release, but we should be able to release more frequently once our new PRONOM analyst joins.

**Comment by oskarhek** [comment]
thank for the update

**Comment by tnafrancesca** [comment]
Just to confirm that this issue was resolved in the 27th October 2021 (v.98 release) and therefore can be closed?
