### ISSUE TITLE
Inconsistency in archives content identifications

### ISSUE THREAD

**Issue by jcharlet** [digital-preservation/droid#471]
https://trello.com/c/1A2pined/75-inconsistency-in-archives-content-identifications
> Command line version of droid in nonProfile mode use some custom base identification for content in archives. We should refactor this code to have only one code for archives(zip,gzip,7zip,warc,arc,iso, ...). At the moment only zip,tar,gzip is supported.
> 
> https://github.com/rhubner/droid/tree/master/droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive
> 
> 
> Why result printer submitting identification??
> https://github.com/rhubner/droid/blob/master/droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/ResultPrinter.java#L153
> 
> Probably similar behaviour for containers.
> https://github.com/rhubner/droid/tree/master/droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/container
> 

as discussed in #375 we probably want to get rid of no profile mode. But we might have this inconsistency issue in the GUI too.

**Comment by jcharlet** [comment]
related to https://github.com/digital-preservation/droid/issues/470

**Comment by CaptainBrad** [comment]
closing as #631 is closed which includes this issue.
