### ISSUE TITLE
inconsistency in archives content identifications

### ISSUE THREAD

**Issue by sparkhi** [digital-preservation/droid#486]
https://trello.com/c/1A2pined/75-inconsistency-in-archives-content-identifications #486

The classes for management of each archive format exist in the GUI and the code is copied into the CLI (for no-profile mode only). The aim is to keep one copy in common module and consume it from both places. 

[UPDATE Jeremie] add link in description

**Comment by nishihatapalmer** [comment]
I've now got the command line using the profile machinery for all identification work, but without writing to the database and instead outputting directly to CSV.  Once tested and accepted, we can remove all the existing command line code for archive file processing and file type identification.  The GUI and the command line will share the same code for this.

**Comment by rhubner** [comment]
Fixed in #743
