### ISSUE TITLE
Subtle bug when upgrading ANTLR from 3.2 to 3.5

### ISSUE THREAD

**Issue by anjackson** [digital-preservation/droid#49]
DROID depends on [ANTLR](http://www.antlr.org/) 3.2. When integrating DROID into my indexer, ANTLR 3.5 got on the classpath and took precedence. Extremely oddly, this somehow prevented DROID from correctly identifying MP3 files! In particular, this file:

http://web.archive.org/web/19991114114525/http://edinburgh-places.co.uk///scotus/trkd.mp3

...was not being identified as audio/mpeg. Other formats were still being identified just fine, as far as I can tell, although I only tried a few.

Just thought I'd let you know in case you are planning to upgrade ANTLR.

**Comment by DavidUnderdown** [comment]
ANTLR dependency now removed in 6.2 and later
