### ISSUE TITLE
License check doesn't allow 2020 date

### ISSUE THREAD

**Issue by nishihatapalmer** [digital-preservation/droid#492]
I get license check failures when I put 2020 as the copyright date in the license header.

**Comment by DavidUnderdown** [comment]
we've had issues around this before, see #286

**Comment by jcharlet** [comment]
This has to be done across all files, and in the resource used to validate headers, see https://github.com/digital-preservation/droid/pull/357 .
Should we improve the template to allow any date? we didn't explore last time we updated all files.

**Comment by adamretter** [comment]
You need to choose a single fixed year. Typically I mostly see people use the inception year of the project.

**Comment by nishihatapalmer** [comment]
Closing this.  Policy is that the year doesn't change on the licence header, no matter when the code is written or updated.
