### ISSUE TITLE
Unit tests fail if cannot connect to DROID update server

### ISSUE THREAD

**Issue by ross-spencer** [digital-preservation/droid#53]
Hi,

We've two issues which result in DROID being unable to connect to its update server. Proxy settings, and whitelisting of sites. 

This isn't a problem running DROID standalone as we can download signature files manually. It is a problem when building the tool. As the Unit tests seem to fail when trying to connect to the server for updates. 

I am unsure if this is a call for the issue to be fixed. I can see why the tests shouldn't fail if they cannot connect to the server, and equally exactly why they should! Is there a middle ground that ensures a graceful completion of the unit tests without them failing? 

Attached screenshots. 

![screenshot from 2014-09-12 16 07 14](https://cloud.githubusercontent.com/assets/1880412/4245260/8385077e-3a33-11e4-8d05-9c84d4e4cec7.png)
![screenshot from 2014-09-12 16 07 57](https://cloud.githubusercontent.com/assets/1880412/4245261/8386458a-3a33-11e4-9d8c-c80b41fc9eb9.png)

**Comment by paulyoung84** [comment]
This issue has been added to the DROID backlog, it will be assigned an appropriate priority but is unlikely to be included in the next release.
