### ISSUE TITLE
CDX Internet Archive Index (fmt/869) falsely recognised as CorelDraw Compressed Drawing (x-fmt/31)

### ISSUE THREAD

**Issue by oschihin** [digital-preservation/droid#530]
This is an issue I already sent to PRONOM in February 2018 (ref number TNA1519295080F73). No action has been taken and our ingest of web archives has been blocked for other reasons anyway. We're taking things up now, so this issue blocks our efforts anew:

DROID validates a file with a `*.cdx`-ending as [`x-fmt/31`](https://www.nationalarchives.gov.uk/PRONOM/Format/proFormatSearch.aspx?status=detailReport&id=62). It is part of of our internet archiving and obviously meant to be [`fmt/869`](https://www.nationalarchives.gov.uk/PRONOM/Format/proFormatSearch.aspx?status=detailReport&id=1673). According to PRONOM, `fmt/869` ought to start with hex `0x20` (space char), followed by the string `CDX`. In our example, it starts directly with `CDX`, so the required space char is missing. This is probably due to an old version of web curator that we use for harvesting. If I add a preceding space, it is recognised correctly. 

So two points: 
* If I check the signature in the xml (see internal signature id=1229), the starting `0x20` is mandatory. Maybe it should be optional, with just the starting string `CDX`? 
* If not recognised correctly, DROID falls back to `x-fmt/31`, simply based on file ending. This is really far off of what it can be. In the end, it's "just" an ASCII text file, and any digital preservation is better served by registering as such, than as a complicated and vendor-based format.

I'll add one of the files, packed into a zip for upload.
[IAH-20151224030341-00000-pdstavs09.zip](https://github.com/digital-preservation/droid/files/5260624/IAH-20151224030341-00000-pdstavs09.zip)

Is there another way to deal with this problem, i.e. by adapting signature files locally or defining a signature that mapts to the format for that particular file?

**Comment by Dclipsham** [comment]
Hi Oliver, Thank you for raising this again. I'm sorry it hasn't been addressed yet. I have created an additional identification signature in PRONOM for CDX that omits the opening 'space' character. This will be included in the next PRONOM release that should be available within the next fortnight. I hope this helps. 

It is possible to edit your DROID signature files, which can be found in the directory <userhome>/.droid6/signature_files, however each official PRONOM signature release would mean that the new signature file wouldn't include your changes, so if you choose to do so it is important to be aware of this and to plan for a degree of intellectual control. 

David

**Comment by oschihin** [comment]
Hi David

Thanks for the quick reaction, that sounds great. I'll see what path to follow. On our ingest servers, we're still running droid 6.3, and, as they have no internet connection, I have to update signatures manually anyway (download and copy). So I'll check for updates on pronom in October.

Oliver

**Comment by oschihin** [comment]
@Dclipsham to let you know, this is how I manually updated the signature. This matches with or without leading space, but not with two:

```xml
<InternalSignature ID="1229" Specificity="Specific">
    <ByteSequence Reference="BOFoffset">
        <SubSequence MinFragLength="0" Position="1" SubSeqMaxOffset="1" SubSeqMinOffset="0">
            <Sequence>43445820</Sequence>
            <DefaultShift>5</DefaultShift>
            <Shift Byte="43">4</Shift>
            <Shift Byte="44">3</Shift>
            <Shift Byte="58">2</Shift>
            <Shift Byte="20">1</Shift>
        </SubSequence>
    </ByteSequence>
</InternalSignature>
```

**Comment by oschihin** [comment]
@Dclipsham this seems to be solved by V97. Tested, and it works! Thanks, I'll close here.
