### ISSUE TITLE
How to add a signature?

### ISSUE THREAD

**Issue by lassik** [digital-preservation/droid#533]
How are signatures added to the PRONOM database? I submitted the web form in April but haven't heard back. We have a format, [Unisig](https://github.com/unisig/unisig) that is identified by the seven bytes `DC DC 0D 0A 1A 0A 00` at the very beginning of a file.

If the eighth byte is zero, a UUID (aka GUID) follows. If the eighth byte is nonzero, a string of that many ASCII characters follows. The UUID and ASCII string may be displayed to the user if supported.

Here are the detection patterns for the Unix [`file`](https://en.wikipedia.org/wiki/File_(command)) program: https://github.com/file/file/blob/master/magic/Magdir/unisig

**Comment by Dclipsham** [comment]
Hi Lassi,

I'm sorry you haven't heard back yet. I can see your submission was received and it is in our research backlog. I'll ensure one of our researchers tackles it for the next release, which should be within the next month or so. Are you able to direct me at any samples for the format?

**Comment by Dclipsham** [comment]
in #pronom v98 - https://www.nationalarchives.gov.uk/PRONOM/fmt/1478
