### ISSUE TITLE
BUG: command line filter parser cannot handle strings with more than one space.

### ISSUE THREAD

**Issue by nishihatapalmer** [digital-preservation/droid#580]
If you try to filter a profile with a filename with more than one space in it, we get an exception.  It can handle a name with a single space, using:

```droid -p "/home/user/myprofile.droid" -E "/home/user/myprofile.csv" -f "file_name = 'a name'"```

Whereas this fails:

```droid -p "/home/user/myprofile.droid" -E "/home/user/myprofile.csv" -f "file_name = 'a name with several spaces'"```

This is because of the regex in SimpleSqlFilterParser that splits up the parameters.  After one space, it terminates the parameter, and puts the rest of the filename into another parameter.

I will fix this in my work on the no profile mode replacement.

**Comment by nishihatapalmer** [comment]
This is now fixed in the no profile mode replacement code (PR yet to be submitted).

**Comment by sparkhi** [comment]
Tested in the current release candidate, it works. 👍🏼
