### ISSUE TITLE
Profile is saving slowly in the network folder

### ISSUE THREAD

**Issue by DenysShvorack** [digital-preservation/droid#60]
Hi

We are using droid-command-line in our company and we discovered a very slow performance, after investigation we found that most of the time is spend on saving profile to the network folder. See more details below.

In our case we are running droid-command-line to times for each file:

1) Specifying file name to analyse and profile name to store results, both where stored in the network folder.
  Example of running command:
java -jar "C:\Program Files (x86)\The National Archives\DROID6\droid-command-line-6.1.jar" -a "\\192.168.2.38\264150\content\dLZA-R1_Liste-offene-Probleme_20140716.xls" -p "\\192.168.2.38\FileIdentifier\8666b03d-8d86-4168-a74c-a23692655024.droid"

2) Specifying name to the 'csv' file and profile name from the previous command, both where stored in the network folder.
   Example of running command:
java -jar "C:\Program Files (x86)\The National Archives\DROID6\droid-command-line-6.1.jar" -E "\\192.168.2.38\FileIdentifier\8666b03d-8d86-4168-a74c-a23692655024.csv" -p "\\192.168.2.38\FileIdentifier\8666b03d-8d86-4168-a74c-a23692655024.droid"

- Running this two commands for one file took about three minutes.
- After changing profile name to the local folder, total time became around 12 seconds.

As I sayd we solved with this issue with changing profile name to the local folder, but I thought that you would like to know about it.

**Comment by alexgreenDP** [comment]
This appears to be a network problem as you indicated. We have not received any other reports of similar issues.
