### ISSUE TITLE
DROID CLI: Archive files (zip, tar, etc) identification data not being returned (CSV)

### ISSUE THREAD

**Issue by vladox** [digital-preservation/droid#61]
Hi 

We are using DROID from the command line invoking "droid-command-line-6.1.3.jar".
The full command being: e.g. C:\Program Files\Java\jre6\bin\java.exe  -jar "droid-binary-6.1.3-bin\droid-command-line-6.1.3.jar" -a "new.zip" -p "08405e1c-3a09-4bdb-a68a-69220903ed9e.droid"

The problem we are facing is that zip files are not returned in the result CSV file, it's either the contents of the file identified or when (profile.processArchives = false)  is set to false in droid.properties then nothing at all is returned.

![](https://lh5.googleusercontent.com/-e2eb8JBxJhw/VCqJ_hNsr-I/AAAAAAAAGhk/gexvmrUyvkQ/s1600/30-09-2014%2B12-44-51.png)

Is there a way to force DROID to return the file identification data for archive files types or is this really a bug?

Best regards
Vladimir

**Comment by seamang** [comment]
Your command line works for me on the current DROID (6.1.5). Your problem might be related to one of the bugfixes that was included in that release - is it possible for you to try upgrading?

Best
Graham

**Comment by DavidUnderdown** [comment]
Presume this was OK in the later version as suggested
