### ISSUE TITLE
Feature request: Mark empty folders

### ISSUE THREAD

**Issue by mappleby** [digital-preservation/droid#63]
It would be very helpful if DROID could detect empty folders, and mark them as such in the csv output.

This is so that I can locate and remove these folders as part of a digital accession to The National Archives.  It is not something that Windows 7 search supports.

Thanks,

Michael

**Comment by Dclipsham** [comment]
Thanks Michael,

I'd expect it would also need to account for scenarios where an otherwise empty folder may contain one or more empty child folders of its own (i.e. no 'files' anywhere in the descendant tree). 

Additionally while I understand the post-processing expectation might be to delete empty folders, either manually or by some kind of batch processing (which is absolutely out of scope for DROID), there may be situations where that isn't desirable, for example temp folders modified on the fly by some systems processes.

David

**Comment by ross-spencer** [comment]
+1 for this feature to be added. Archives New Zealand.

**Comment by nishihatapalmer** [comment]
A workaround would be to use SQL to detect ids which have no other parent_id set to them.  Either by directly connecting to the DROID profile apache derby database, or by importing the CSV export into a database.

This seems to work using DBVisualiser on a DROID profile:

```SELECT NODES.* FROM PROFILE_RESOURCE_NODE AS NODES
WHERE RESOURCE_TYPE = 0 AND
NOT EXISTS (SELECT PARENT_ID FROM PROFILE_RESOURCE_NODE WHERE PARENT_ID = NODES.NODE_ID)```

**Comment by ross-spencer** [comment]
Hi Matt, 

By coincidence, I implemented the code in Python the other day. It has other features, including, pre-empting deletions using blacklists. I'm working on the unit tests as we speak. 

https://github.com/exponential-decay/detect-empty-folders

Ross

**Comment by mappleby** [comment]
Hi Matt, Ross,
Thanks for your messages.  Must admit, I did not consider looking at the DROID database.
I did a workaround in the end, using MSDOS 'rd' command and relying on the fact it won't delete a folder that isn't empty.  I'm not sure this is an approach that should be encouraged!  
(I used the advice on this page, incidentally: http://www.pcmag.com/article2/0,2817,803393,00.asp.  It has a good tip to do a reverse sort on the folder path list first, so that there's no need to worry about recursing through looking for parents that only contain empty folders).

**Comment by paulyoung84** [comment]
This issue has been added to the DROID backlog, it will be assigned an appropriate priority but is unlikely to be included in the next release.

**Comment by rhubner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#63 Feature request: Mark empty folders](https://trello.com/c/FNSGN1y9/25-63-feature-request-mark-empty-folders)

**Comment by DavidUnderdown** [comment]
In test

**Comment by rhubner** [comment]
6.4
