### ISSUE TITLE
KML mime type

### ISSUE THREAD

**Issue by pwinckles** [digital-preservation/droid#645]
Is there a reason the KML format does not have a mime type defined?

```xml
        <FileFormat ID="975" Name="Keyhole Markup Language (XML)" PUID="fmt/244">
            <InternalSignatureID>574</InternalSignatureID>
            <Extension>kml</Extension>
            <HasPriorityOverFileFormatID>638</HasPriorityOverFileFormatID>
        </FileFormat>
```

I believe it should be `application/vnd.google-earth.kml+xml`.

**Comment by Dclipsham** [comment]
Thanks Peter, we'll add that in to the next PRONOM release.

David

**Comment by Dclipsham** [comment]
in #pronom v98 - https://www.nationalarchives.gov.uk/PRONOM/fmt/244
