### ISSUE TITLE
Current DROID cannot open profiles created by other versions (ProfileWebArchives issue).

### ISSUE THREAD

**Issue by nishihatapalmer** [digital-preservation/droid#68]
When the latest code in the repository attempts to open a profile created by another version of DROID, it fails with a NullPointerException.

This is because it's looking for a new property ProfileWebArchives in profile.xml, which doesn't exist.  It then gets a null Boolean return value, which causes a NullPointerException when it attempts to set this on the submissiongateway.

It should default to false for a property which may or may not exist.  Or true, if you prefer - but there should be a default value for properties which are optional.

**Comment by seamang** [comment]
Fixed in pull request 64
