### ISSUE TITLE
Empty folders viewable in GUI but not in export

### ISSUE THREAD

**Issue by adesousa576** [digital-preservation/droid#707]
Currently when you run DROID you can see if there are any empty folders because they are red with a 0 through them
But when you export that as a report eg. csv I can’t see that captured in the output – unsure if I’m missing it or if it doesn’t translate to the report? If the latter is there anyway a column could be added like empty_folder and it be populated YES if the folder was empty? 

Think this is a useful feature for internal and external users, especially when dealing with large volumes. Thanks!

**Comment by Dclipsham** [comment]
Need's careful handling as peoples' workflows may depend on expectation of data in specific CSV column output so changes here need to be well publicised

**Comment by adesousa576** [comment]
> Needs careful handling as peoples' workflows may depend on expectation of data in specific CSV column output so changes here need to be well publicised

100% agree - ideal would be a new column at the end of the current output that way shouldn't interfere with current processes e.g. DROIDConvert.py or any of the TDR output etc or expectations of column order externally

**Comment by k-pendergrass** [comment]
Using DROID 6.4 on Windows 10, I am seeing the enhancement you ask for as standard behavior. I've run a couple of tests and the empty directories appear in both the DROID GUI and csv output in all cases:
- Empty directory created via Windows file explorer GUI
- Empty directory created via Windows CLI
- DROID export as one line per file
- DROID export as one line per format

Here is a snip of the output:
"FILE_PATH","NAME","METHOD","STATUS","SIZE","TYPE"
"[my-local-path\desktop\empty-dir","empty-dir",,"Empty",,"Folder"
"[my-local-path\desktop\empty-dir-cmd","empty-dir-cmd",,"Empty",,"Folder"

The value Empty in the Status field provides the indication that the directory is empty.

**Comment by Dclipsham** [comment]
Ah ha! Thanks Keith, confirmed in 6.5.1 also:
![empty](https://user-images.githubusercontent.com/2189778/151531174-6c8eb0e7-a4eb-4670-86c6-f22954812cd5.png).

@adesousa576 I'll close this...
