### ISSUE TITLE
multi-part zip issue blocks update of apache commons compress library

### ISSUE THREAD

**Issue by seamang** [digital-preservation/droid#71]
DROID currently uses the apache commons compress library version 1.4.1. There are various zip features not supported in this version (raising  UnsupportedZipFeatureExceptions) which are supported in the current version 1.10, and which would improve DROID's performance with zip files.

Unfortunately 1.5 introduced a change to handling of multi-part zips:
"Split/spanned ZIP archives are now properly detected by ArchiveStreamFactory but will cause an UnsupportedZipFeatureException when read."

Multipart zips have previously caused problems for DROID users and are explicitly tested for in the test suite; the test fails on any version after 1.4.1.  Presumably 1.4.1 simply masked a real problem by not correctly recognizing multipart zips. Need to find example files to assess impact of updating the library.

**Comment by paulyoung84** [comment]
see also #100

**Comment by rhubner** [comment]
Not relevant anymore, we are using TrueZip #144
