### ISSUE TITLE
Upper case extensions in filters never work

### ISSUE THREAD

**Issue by gmcgath** [digital-preservation/droid#75]
In the GUI version of DROID 6.1.5, if I use an upper-case extension in a filter, it never matches. Only strictly lower-case extensions will match, even if the files user upper-case extensions. This is neither consistently case-sensitive nor consistently case-independent. A case-independent comparison seems to be what's intended.

**Comment by gmcgath** [comment]
This may be related to issue #70

**Comment by snail1966** [comment]
Apologies for not getting back earlier.  We are hoping to introduce case insensitive filtering in the next release of DROID.   This is subject to testing which, amongst other things, will need to establish that there is no noticeable performance impact.  The default behaviour of the Apache Derby database used in DROID profiles is case sensitive - this explains the current behaviour in the filter and elsewhere, including issue 70 (file extensions being forced to lower case for consistency).  It is not proposed to change case sensitivity behaviour in apsects other than filtering in the forthcoming release - this would require more extensive code changes and testing, and there are also more philosophical issues involved (e.g. should a .TXT and txt extension be treated as being the same for exports, report aggregations etc?), Regards Brian

**Comment by snail1966** [comment]
This issue should now be fixed in the latest release candidate (code at https://github.com/snail1966/droid).  This is currently being tested - hopefully it will be released around the end of this month.
Regards, Brian
