### ISSUE TITLE
DROID API

### ISSUE THREAD

**Issue by rhubner** [digital-preservation/droid#752]
Create API for easy DROID integration by other teams in The National Archives.

- This API will not be treated as stable or public and no guarantee will be provided to 3th party software.
- API can change or be removed any time and no support will be provided outside of TNA.
- All API will be marked with anontation as internal.
- External developers should not use this API and wait for DROID 7 with more modularity and stable API.

**Comment by sparkhi** [comment]
This is available in 6.6.0
