### ISSUE TITLE
Exporting to csv with hash sha256 using the command line

### ISSUE THREAD

**Issue by marcelomgarcia** [digital-preservation/droid#762]
We automating our digital preservation workflow with a Python script, and one the steps is to run "droid" command line.

I can't find a way to export the profile to csv with the "hash" sha256 option. On the GUI it's an option, how to enable it via command-line? Is there a way to enable hash once I have the profile?

**Comment by marcelomgarcia** [comment]
I tried to change `options.properties` , and recompiled `droid`, to generate the hash values but without success

```
profile.generateHash = true \n \
profile.hashAlgorithm = sha256 \n 
```

**Comment by marcelomgarcia** [comment]
Interestingly in `droid-command-line\src\main\resources\options.properties` has an example:

```
profile.property.help=(...)For example, to override the max bytes to scan parameter,\n  \
droid -Pr "profile.maxBytesToScan=32768" -a "C:\\Files\\A Folder" -p "C:\\Results\\result1.droid"
```
But if try to use the `-Pr` option:
```
PS C:\Users\garcm0b\Work\droid-binary-6.5.2-bin-win32-with-jre> .\droid.bat -Pr "profile.generateHash=true" -a "C:\Users\garcm0b\Work\013_002_0026" -p "C:\Users\garcm0b\Work\013_002_0026\013_002_0026.droid"
2022-04-20T13:37:11,837  INFO [main] DroidCommandLine:140 - Starting DROID.
Incorrect command line syntax: org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -Pr
PS C:\Users\garcm0b\Work\droid-binary-6.5.2-bin-win32-with-jre>
```

Also, when I use `droid.bat -h` I don't see the part about changing properties.

**Comment by nishihatapalmer** [comment]
I just did a quick test on the latest 6.5.2 freshly downloaded and I also got this error.

Strange - the code seems to have all the profile property processing bits.   Looks like some kind of bug somewhere.

**Comment by sparkhi** [comment]
This works in the newer version. I just tried a command line of following nature: 
```
./droid.sh -Pr "profile.generateHash=true" "profile.hashAlgorithm=sha256" -a <path to the file to be identified> -p <path to the generated profile>
```

and it works. Hence closing this issue
