### ISSUE TITLE
Use embedded jre for sigtool

### ISSUE THREAD

**Issue by sparkhi** [digital-preservation/droid#809]
Just to mention that in our current 6.5.2 package with JRE embedded, although droid.bat correctly calls the embedded JRE to run DROID…
 
start "" "%DROID_HOME%/jre/bin/javaw" %DROID_OPTIONS% -jar "%DROID_HOME%droid-ui-6.5.1.jar" 
 
…the sigtool.bat file assumes you have Java installed. 
 
java -jar droid-tools-6.5.2.jar %*
 
Probably worth fixing in the next release.

**Comment by paulwellsagilej** [comment]
I have made the change to the batch file to use the embedded jre. I am now testing the change .

**Comment by paulwellsagilej** [comment]
This is now tested on Windows. Next: working on the shell script.

**Comment by paulwellsagilej** [comment]
Supporting embedding a JRE other than Windows is out of scope for this ticket.

**Comment by paulwellsagilej** [comment]
After a conversation with @sparkhi I now have more information about how the runnable files are built. I am fairly sure at this stage that the sigtool.bat itself is complete. However, the way the files are assembled and packaged still needs to be checked.

**Comment by paulwellsagilej** [comment]
I found some inconsistencies in the way DROID was being built and the way sigtool was being built - it looks like someone made a change for DROID but forgot to mirror the change for sigtool.  I have now pushed a new change to the assembly which addresses the inconsistency.

**Comment by ross-spencer** [comment]
It looks like an updated `.bat` for sigtool sn't in the 6.6.0-rc2 binary, but to confirm if someone wants to run the sigtool with something like the droid.bat file: https://github.com/digital-preservation/droid/blob/0a9b384f9eea52ad0e1c044fba4b3ea13031b4dc/droid-binary/bin/droid.bat then the changes are fairly trivial, but perhaps it's a good idea to maintain an optimized sigtool batch file with only some of these options.

**Comment by steve-daly** [comment]
That change to sigtool.bat should be coming in 6.6.1 but we didn't want to make any further changes while trying to get 6.6.0 over the line.

**Comment by paulwellsagilej** [comment]
An update from me on this - running a build should trigger a maven assembly which packages up all files in a distribution. However, I'm not seeing any of the scripts included when I run a local build. I will need to resolve this before I can test that the updated scripts will be correctly available in the distribution.
