### ISSUE TITLE
Utilize version number within container signature file XML?

### ISSUE THREAD

**Issue by ross-spencer** [digital-preservation/droid#83]
I notice that the signatureVersion field inside the container signature file is never updated. Does this field have a described purpose/schema description? Can the version number of the file be placed here as a mechanism of placing the version inside the file as well as the file naming convention?

From the latest signature file: 

    <?xml version="1.0" encoding="UTF-8"?> 
    <ContainerSignatureMapping schemaVersion="1.0" signatureVersion="1">

**Comment by alexgreenDP** [comment]
In use as of PRONOM signature release 29/6/16.
