### ISSUE TITLE
Change to the CSV export

### ISSUE THREAD

**Issue by CaptainBrad** [digital-preservation/droid#861]
Currently, if you ask for 'one row per file', any additional identified formats are added as extra columns - but they are not given a column header.  Can this be included, e.g. PUID2 etc.  The missing header makes the csv difficult to use in Excel and also for scripting where you have to work around the missing headers (e.g. Python pandas read_csv).  I'm using 6.5.2.

**Comment by ross-spencer** [comment]
@CaptainBrad this looks like it's connected to: https://github.com/digital-preservation/droid/issues/118 there's some additional discussion there.

**Comment by CaptainBrad** [comment]
Thanks for the heads up @ross-spencer , we will look into 118.

**Comment by paulwellsagilej** [comment]
I understand the problem now and I have investigated and started making changes to add the missing header values. The number of columns will vary from one CSV file to another, but each file will be valid within itself. The number of values in each row will match the number of values in the header row.

**Comment by paulwellsagilej** [comment]
Existing tests pass now. Working on new tests to check new behaviour.
