### ISSUE TITLE
FORMAT_COUNT column not populated in 6.2 if there is no match

### ISSUE THREAD

**Issue by ross-spencer** [digital-preservation/droid#88]
See: 
![image](https://cloud.githubusercontent.com/assets/1880412/13166748/214c2240-d730-11e5-853d-0570224e5dff.png)

FORMAT_COLUMN does not seem to output a '0' if there are no matches. This is likely to break compatibility with anyone utilizing this version of DROID's CSV output.

**Comment by snail1966** [comment]
Thanks for pointing this out - although this output isn't guaranteed to be exactly compatible between releases I'd agree it is reasonable to record a 0 in such cases so will take on board for the next point release.
Regards, Brian

**Comment by snail1966** [comment]
This issue is also fixed in Release candidate 6.2.1 - https://oss.sonatype.org/service/local/repositories/ukgovnationalarchives-1022/content/uk/gov/nationalarchives/droid-binary/6.2.1/droid-binary-6.2.1-bin.zip
This will be formally released shortly, Regards, Brian

**Comment by ross-spencer** [comment]
I can confirm this is fixed:

![image](https://cloud.githubusercontent.com/assets/1880412/13591105/7694e994-e54a-11e5-8010-2d28324f1f6b.png)
