### ISSUE TITLE
DROID 6.6.0-rc binaries?

### ISSUE THREAD

**Issue by ross-spencer** [digital-preservation/droid#884]
Hi folks - can anyone point us at the best place to access the DROID 6.6.0-rc binaries for testing? (Or perhaps attach them to the releases page?)

**Comment by steve-daly** [comment]
The latest RC2 is here...  

https://oss.sonatype.org/service/local/repositories/releases/content/uk/gov/nationalarchives/droid-binary/6.6.0-rc2/droid-binary-6.6.0-rc2-bin-win32-with-jre.zip

and 

https://oss.sonatype.org/service/local/repositories/releases/content/uk/gov/nationalarchives/droid-binary/6.6.0-rc2/droid-binary-6.6.0-rc2-bin.zip

We're looking to address #877 in an RC3 soon

**Comment by ross-spencer** [comment]
Thanks @steve-daly 🙇🙏

**Comment by sparkhi** [comment]
Done
