### ISSUE TITLE
Hyperlinks for multiple-identifications only lead to one URL in DROID front-end

### ISSUE THREAD

**Issue by ross-spencer** [digital-preservation/droid#885]
If you have an identification in the DROID-UI, there is a link in the PUID column that leads to the PUIDs record in PRONOM. For a multiple-identification this is comma-separated-list as per the image below. In this instance, the PUID DROID leads you to is the last one in the list, and there aren't separate links for each PUID.

![image](https://user-images.githubusercontent.com/1880412/217521737-de7eea2a-60a0-4ab7-bf00-9d2daa8224b0.png)

Tested on recent skeleton-suite files, attached: 

[2023-02-08-multi-id-containers.zip](https://github.com/digital-preservation/droid/files/10685131/2023-02-08-multi-id-containers.zip)

**Comment by sparkhi** [comment]
Hi @ross-spencer 
I've tried this on Ubuntu 22.04.1 LTS, Chrome as a default browser and It opened multiple tabs in chrome with one each for each of the PUID. 
You are right that it does not show the values as hyperlinked and I suspect that is probably down to limitation of the view (can't confirm yet). Can you please tell us which browser you used and whether there is something around specific browser that may be a problem.  
Thanks,

**Comment by ross-spencer** [comment]
ah, thanks @sparkhi I suspect two tabs were opening and I was not noticing. A little bit confused by the UI perhaps, i.e. anticipating two separate links. 

The Java bin hasn't been released officially yet? https://github.com/digital-preservation/droid/releases/tag/droid-6.6.0 -- I can try this given availability of that to confirm as this was on 6.6 and I only have access to 6.5 at the moment.

**Comment by sparkhi** [comment]
We are in the process of releasing a quick patch (6.6.1) soon, mainly to fix #900 so you could either hold off or try 6.6.0 if you prefer

**Comment by ross-spencer** [comment]
If you're okay holding on @sparkhi I can wait for the patch to briefly confirm?

**Comment by ross-spencer** [comment]
Investigated on 6.6.1 today and the behavior described by @sparkhi is correct. User error on my part. Closing as this was primarily interested in the opening of one link over the other rather than other potential Ux improvements here. 

![image](https://user-images.githubusercontent.com/1880412/226560638-de7e46ad-73e6-4842-8e7c-42a8e03cbb90.png)
