### ISSUE TITLE
ARC file handler - infinite loop

### ISSUE THREAD

**Issue by Brian-O-TNA** [digital-preservation/droid#90]
It is possible for DROID to hang with an infinite loop in the ARC File handler code, under certain circumstances.  So far this has only been observed in 'skeletal' ARC files which although being recognised as conforming to the ARC signature, do not contain key elements e.g. a header that one would expect in real world ARC files.  The issue has not been observed with any "real" ARC files used for evaluation so far.  Nonetheless, it is being flagged up here as a known issue, to be investigated further and fixed in a future release.
Regards, Brian

**Comment by Dclipsham** [comment]
closing as not encountered IRL but potial to reopen if encountered in wild
