### ISSUE TITLE
DROID 6.6 failing to consistently output HASH column to CSV

### ISSUE THREAD

**Issue by Dclipsham** [digital-preservation/droid#900]
DROID 6.6, embedded JRE 11 GUI version, Windows 10 22H2:
Preferences:
![image](https://user-images.githubusercontent.com/2189778/222734287-a4926a07-db65-4d17-8703-00292b495600.png)

GUI behaviour (Hash present): 
![image](https://user-images.githubusercontent.com/2189778/222734498-7aa4c5cd-7122-4421-9369-cf4cd0d3ef47.png)

Export options:
![image](https://user-images.githubusercontent.com/2189778/222734616-5f8a9b74-ba90-4303-8646-1a3c312e1cdf.png)

CSV Output (also attached):
![image](https://user-images.githubusercontent.com/2189778/222734833-668a195c-5b44-4c9b-889c-b031d467979f.png)

DROID Log (also attached):
![image](https://user-images.githubusercontent.com/2189778/222734951-7a6a9d8b-365e-4485-bfc8-eec68550d1d1.png)

Note that the first time I ran DROID 6.6, the HASH column did successfully export. Subsequent runs did not, and I have not changed any preferences between runs.

I've also tested on DROID 6.5 and behaviour is as-expected. Let me know if you need anything further.

[droid.log](https://github.com/digital-preservation/droid/files/10882440/droid.log)
[v109_EDRM_6.6_test2.csv](https://github.com/digital-preservation/droid/files/10882441/v109_EDRM_6.6_test2.csv)

**Comment by Dclipsham** [comment]
Glad it's not just me! Curious one...

**Comment by steve-daly** [comment]
Hi @Dclipsham out of interest, do you find Checksum generation totally reliable in 6.5.2?  We can see this issue that has arisen in 6.6.0 but as we've discussed this people have mentioned intermittent unreliability with checksums in 6.5.2, and maybe worse when analysing subfolders too.

**Comment by Dclipsham** [comment]
I haven't noticed checksum issues with 6.5.x or earlier versions myself. Certainly my first time seeing that warning message in the logs

**Comment by sparkhi** [comment]
Fixed in 6.6.1
