### ISSUE TITLE
Both March 2023 container signatures have the same signatureVersion

### ISSUE THREAD

**Issue by Dclipsham** [digital-preservation/droid#924]
The container signature files:
https://cdn.nationalarchives.gov.uk/documents/container-signature-20230307.xml
https://cdn.nationalarchives.gov.uk/documents/container-signature-20230316.xml

..each have signatureVersion set at '33'. This should increment on each release. 

For convenience I include an updated signature file (zipped due to GitHub upload limitations) with signatureVersion set to 34. This version also corrects the issue raised in https://github.com/digital-preservation/droid/issues/923

[container-signature-20230323.zip](https://github.com/digital-preservation/droid/files/11054665/container-signature-20230323.zip)

I've set it to today's date. For continuity purposes you may wish to remove the one dated 20230307 since the one dated 20230316 was publicised and therefore likely to have been downloaded more often than 20230307. This would hopefully mitigate issues with multiple Container Signature files with a single signatureVersion being available, and would mean the following files have the following signatureVersions:
20221102 - 32
20230316 - 33
20230323 - 34

Alternatively you could keep 20230307 in place, update signatureVersion to 34 in 20230316, and update this one to 35.
 
David

**Comment by tnafrancesca** [comment]
Two container signatures were uploaded, but were exactly the same. We have now taken down 20230307. I have taken a copy of the container signature suggested and will release it either alongside the next version or as a release by itself. I am going to close this issue now.
