### ISSUE TITLE
'Error occurred whilst establishing connection to PRONOM server.'

### ISSUE THREAD

**Issue by kathaurielle** [digital-preservation/droid#942]
Hello, a user is getting the error above, the one internal users had recently. What can I suggest they try, please? 

![image](https://github.com/digital-preservation/droid/assets/46964067/a3daff6d-6027-4f57-86b1-1700da2bef5b)

![image](https://github.com/digital-preservation/droid/assets/46964067/2afc44d2-814a-4643-acce-aae1716c4697)

**Comment by steve-daly** [comment]
Did this used to work?  Has is stopped working recently?  Is this on a corporate network where an internet proxy or security restrictions could possibly be in use for web access?

**Comment by kathaurielle** [comment]
Thanks! Have asked them.

**Comment by sparkhi** [comment]
It looks like there is no further update, closing this issue
