### ISSUE TITLE
DROID crashes when exporting results to csv

### ISSUE THREAD

**Issue by kathaurielle** [digital-preservation/droid#944]
Hello, can anyone suggest what's happening here, please?:

I stumbled on a java related export error below:

java.nio.file.InvalidPathException: Trailing char < > at index (then gives a filepath to a doc)

I looked for answers on the Google user group to no avail.

 DROID stalls at this point and does not carry on with exporting the results to csv. 
Is there any way of removing this particular path from the DROID report so as to bypass it?

Also - are there any limitations to csv export creation?
The half-completed csv file is 150 MB in size.

<img width="628" alt="Untitled" src="https://github.com/digital-preservation/droid/assets/46964067/b7b8004e-162c-491a-812f-8bf977cbdf1c">

**Comment by steve-daly** [comment]
Can you see which file it's failing on. Could you limit your analysis to just that line (e.g. maybe try the files before and after the last one in the created CSV) to see if it still fails

**Comment by kathaurielle** [comment]
Thanks both! have passed this on.

**Comment by sparkhi** [comment]
Closing this issue.
