### ISSUE TITLE
Issue with CSV export percentage coding reserved characters in uri field

### ISSUE THREAD

**Issue by paulyoung84** [digital-preservation/droid#95]
The uri field in the CSV export of droid results does not percentage encode some reserved characters. For example + should be encoded as %2B

**Comment by rhubner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#95 Issue with CSV export percentage coding reserved characters in URI field](https://trello.com/c/KAamGoW3/4-95-issue-with-csv-export-percentage-coding-reserved-characters-in-uri-field)
