### ISSUE TITLE
CSV export order currently random

### ISSUE THREAD

**Issue by paulyoung84** [digital-preservation/droid#96]
The order in which files appear currently in a csv export is random and different each time it is exported. Request that the export is ordered in a fixed way so that each export would be in the same order.

**Comment by rhubner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#96 CSV export order currently random](https://trello.com/c/pD7kDQk5/9-96-csv-export-order-currently-random)

**Comment by DavidUnderdown** [comment]
In test
