### ISSUE TITLE
NEW PROFILE INSTALLATION

### ISSUE THREAD

**Issue by snail1966** [digital-preservation/droid#97]
DROID 6.2.x sometimes fails to return any identifications on the first profile run in the GUI after a new signature file is installed via the Tools menu. Further profiles thereafter work normally.

**Comment by ross-spencer** [comment]
Hi Brian, I'm glad this has been reported. I have noticed the same behavior but had no way to remove my own environments as a potential interference. I usually start signature development testing by deleting all folders except for my two signature folders under .droid6.

**Comment by snail1966** [comment]
This should now be fixed in the build at https://github.com/snail1966/droid/tree/newSigFileIssue .  It is intended to include this in the next release, subject to further testing.

**Comment by paulyoung84** [comment]
Fixed in 6.3
