### ISSUE TITLE
Strange toolbar behaviour in 6.7.0-RC3

### ISSUE THREAD

**Issue by sparkhi** [digital-preservation/droid#993]
It appears that the toolbar is detachable in 6.7.0-RC3, however, once it is detached from the main window, it does not fit back in the original way. The profile window overlaps it as shown in the screenshot. This makes the toolbar unusable.

Make the toolbar work same as earlier releases.

![image](https://github.com/digital-preservation/droid/assets/4743002/aefc7143-5fc4-447b-8cf7-d8f35ca616ac)

**Comment by thorsted** [comment]
Confirmed on Mac OS X running jdk 18.0.2.1+1-1
![Screenshot 2023-08-03 at 10 10 53 AM](https://github.com/digital-preservation/droid/assets/213296/4fecfe96-7e32-48e0-91cb-929214b05351)

**Comment by sparkhi** [comment]
**developer note**: it looks like the default value for isFloatable may have changed (why??). 
We do not explicitly set the `floatability` to true or false, perhaps we need to set it explicitly now
